@echo off
rem ===================================================================
rem  Speakalive build script (MSVC, 32-bit, no-CRT, Windows 2000+).
rem
rem  Produces a self-contained Speakalive.exe that depends only on DLLs
rem  present on Windows 2000 (kernel32/user32/gdi32/comctl32/comdlg32/
rem  ole32/oleaut32/advapi32/winmm/msacm32).  The C runtime is NOT linked
rem  (/NODEFAULTLIB) because the VC runtime does not exist on Win2000.
rem ===================================================================
setlocal

rem ===================================================================
rem  PROGRAM METADATA - edit these to set the version and file details.
rem  They are written into src\verinfo.h and baked into the .exe's
rem  Properties -> Details (version, description, copyright, and so on).
rem  Avoid the characters & < > | ^ in the text values.
rem ===================================================================
set VER_MAJOR=2002
set VER_MINOR=2
set VER_PATCH=0
set VER_BUILD=0
rem Version string shown in Help -> About Speakalive (edit freely).
set "VERSION=2002.2.0"
set "PRODUCT_NAME=Speakalive"
set "FILE_DESC=Speakalive text-to-speech"
set "COMPANY=Seediffusion"
set "COPYRIGHT=
set "INTERNAL_NAME=cdfn.Speakalive"
set "ORIG_FILENAME=Speakalive.exe"
set "COMMENTS=A revival of Speakonia."
set "VER_STR=%VER_MAJOR%.%VER_MINOR%.%VER_PATCH%.%VER_BUILD%"

rem ---- locate and enter a 32-bit MSVC environment -------------------
set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" (
    echo ERROR: vswhere.exe not found - is Visual Studio installed?
    exit /b 1
)
for /f "usebackq delims=" %%i in (`"%VSWHERE%" -latest -property installationPath`) do set "VSPATH=%%i"
if not defined VSPATH (
    echo ERROR: Visual Studio not found.
    exit /b 1
)
call "%VSPATH%\VC\Auxiliary\Build\vcvars32.bat" >nul
if errorlevel 1 (
    echo ERROR: could not initialise the MSVC 32-bit environment.
    exit /b 1
)

set "SRC=%~dp0src"
set "OUT=%~dp0build"
if not exist "%OUT%" mkdir "%OUT%"
pushd "%OUT%"

rem ---- common compiler flags ----------------------------------------
set CFLAGS=/nologo /c /W3 /GS- /Gy /DWIN32 /D_WIN32_WINNT=0x0500 /DWINVER=0x0500 /DCOBJMACROS
set "SAPI4INC=C:\Program Files (x86)\Microsoft Speech SDK\Include"

rem ---- write the version/metadata header ----------------------------
echo Generating version metadata...
> "%SRC%\verinfo.h"  echo /* Generated by build.bat - edit the variables in build.bat, not here. */
>>"%SRC%\verinfo.h"  echo #define SA_VER_MAJOR     %VER_MAJOR%
>>"%SRC%\verinfo.h"  echo #define SA_VER_MINOR     %VER_MINOR%
>>"%SRC%\verinfo.h"  echo #define SA_VER_PATCH     %VER_PATCH%
>>"%SRC%\verinfo.h"  echo #define SA_VER_BUILD     %VER_BUILD%
>>"%SRC%\verinfo.h"  echo #define SA_VERSION_STR   "%VER_STR%"
>>"%SRC%\verinfo.h"  echo #define SA_VERSION       "%VERSION%"
>>"%SRC%\verinfo.h"  echo #define SA_PRODUCT_NAME  "%PRODUCT_NAME%"
>>"%SRC%\verinfo.h"  echo #define SA_FILE_DESC     "%FILE_DESC%"
>>"%SRC%\verinfo.h"  echo #define SA_COMPANY       "%COMPANY%"
>>"%SRC%\verinfo.h"  echo #define SA_COPYRIGHT     "%COPYRIGHT%"
>>"%SRC%\verinfo.h"  echo #define SA_INTERNAL_NAME "%INTERNAL_NAME%"
>>"%SRC%\verinfo.h"  echo #define SA_ORIG_FILENAME "%ORIG_FILENAME%"
>>"%SRC%\verinfo.h"  echo #define SA_COMMENTS      "%COMMENTS%"

echo Compiling...
rem nocrt.c MUST be unoptimised so its memset/memcpy loops are not turned
rem into self-referential calls.
cl %CFLAGS% /Od "%SRC%\nocrt.c"      || goto :fail
cl %CFLAGS% /O1 "%SRC%\util.c"       || goto :fail
cl %CFLAGS% /O1 "%SRC%\engine.c"     || goto :fail
cl %CFLAGS% /O1 "%SRC%\audiofile.c"  || goto :fail
cl %CFLAGS% /O1 "%SRC%\sapi5.c"      || goto :fail
cl %CFLAGS% /O1 /I"%SAPI4INC%" "%SRC%\sapi4.c"  || goto :fail
cl %CFLAGS% /O1 "%SRC%\onecore.c"    || goto :fail
cl %CFLAGS% /O1 "%SRC%\webread.c"    || goto :fail
cl %CFLAGS% /O1 "%SRC%\main.c"       || goto :fail

echo Compiling resources...
rc /nologo /fo speakalive.res "%SRC%\speakalive.rc" || goto :fail

echo Linking...
link /nologo /NODEFAULTLIB /ENTRY:WinMainCRTStartup ^
     /SUBSYSTEM:WINDOWS,5.00 /MACHINE:X86 /MANIFEST:NO ^
     /OUT:Speakalive.exe ^
     nocrt.obj util.obj engine.obj audiofile.obj sapi5.obj sapi4.obj ^
     onecore.obj webread.obj main.obj speakalive.res ^
     kernel32.lib user32.lib gdi32.lib comctl32.lib comdlg32.lib ^
     ole32.lib oleaut32.lib advapi32.lib winmm.lib msacm32.lib ^
     wininet.lib shell32.lib sapi.lib uuid.lib || goto :fail

echo Patching PE header for Windows 2000 (subsystem 5.0)...
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0tools\patch_pe.ps1" -Path "%OUT%\Speakalive.exe" || goto :fail

echo.
echo BUILD OK -^> %OUT%\Speakalive.exe
popd
endlocal
exit /b 0

:fail
echo.
echo BUILD FAILED
popd
endlocal
exit /b 1
