/* main.c - Speakalive user interface (native Win32, accessible, Win2000+). */
#include <windows.h>
#include <commctrl.h>
#include <commdlg.h>
#include <shellapi.h>
#include <mmsystem.h>

#include "resource.h"
#include "engine.h"
#include "util.h"
#include "webread.h"
#include "verinfo.h"      /* SA_VERSION, generated by build.bat */

#ifndef SA_VERSION
#define SA_VERSION "dev"
#endif

#define APP_CLASS "SpeakaliveWindow"
#define APP_TITLE "Speakalive"

/* Posted by the web-fetch worker thread; wParam is a heap text string or NULL. */
#define WM_SA_WEBDONE (WM_APP + 300)

/* Posted to the progress dialog when a file render finishes.
 * wParam is the BOOL success result, lParam is the format (FMT_WAV/FMT_MP3). */
#define WM_SA_SAVEDONE (WM_APP + 301)

/* Posted to the progress dialog to kick off an inline (UI-thread) render -
 * used for SAPI 4, and as a fallback if a worker thread cannot be created. */
#define WM_SA_DORENDER (WM_APP + 302)

/* Callback message for the notification-area icon used to show the "audio
 * saved" toast (Windows 8+) / balloon (Windows 7 and earlier). */
#define WM_SA_TRAY     (WM_APP + 303)

/* Posted (not called inline) so the save dialog closes instantly and the toast
 * - whose Shell_NotifyIcon call can stall briefly - fires afterwards. */
#define WM_SA_SHOWTOAST (WM_APP + 304)

/* Periodic autosave (crash recovery). */
#define TIMER_AUTOSAVE   1
#define AUTOSAVE_MS      10000
#define TIMER_TRAY       2          /* fallback removal of the tray icon  */
#define TRAY_MS          30000

/* Slider ranges (normalised inside the engines). */
#define RATE_MIN   0
#define RATE_MAX   20
#define RATE_DEF   10   /* 10 -> engine 0 (default speed)  */
#define PITCH_MIN  0
#define PITCH_MAX  20
#define PITCH_DEF  10
#define VOL_MIN    0
#define VOL_MAX    100
#define VOL_DEF    100

/* Dark theme colours. */
#define DARK_BG   RGB(32,32,32)
#define DARK_CTL  RGB(45,45,45)
#define DARK_TXT  RGB(240,240,240)
#define DARK_BTN  RGB(60,60,60)
#define DARK_EDGE RGB(100,100,100)
#define DARK_DIS  RGB(128,128,128)

/* ---- module state ---------------------------------------------------- */

static HINSTANCE g_inst;
static HWND g_main, g_tab, g_voiceLbl, g_voice, g_textLbl, g_text;
static HWND g_rateLbl, g_rate, g_rateVal, g_pitchLbl, g_pitch, g_pitchVal;
static HWND g_volLbl, g_volume, g_volVal, g_reset, g_speak, g_pause, g_stop, g_status;
static HFONT g_font;
static HMENU g_menu;

static WNDPROC g_editOldProc;      /* original edit window proc  */

static SpeechEngine *g_engine;     /* current engine            */
static int  g_engineIndex = -1;
static BOOL g_xmlMode = TRUE;      /* honour SAPI 5 XML / SSML  */
static BOOL g_highlight = FALSE;   /* select the spoken word in the text box.
                                    * Off by default: the selection changes make
                                    * a screen reader talk over the speech. */
static BOOL g_stereo   = FALSE;    /* save audio as stereo (else mono) */
static BOOL g_dirty    = FALSE;    /* text changed since the last autosave */
static BOOL g_modified = FALSE;    /* text changed since the last text-file save */
static BOOL g_speaking = FALSE;
static BOOL g_paused   = FALSE;
static BOOL g_saving   = FALSE;    /* guards re-entry during a file render */
static BOOL g_webBusy  = FALSE;    /* a web page fetch is in flight        */
static HWND g_lastFocus = NULL;    /* control to restore focus to on return*/
static HWND g_progressDlg = NULL;  /* modeless "Saving Audio" dialog, or NULL  */
static NOTIFYICONDATAA g_nid;      /* notification-area icon for save toasts   */
static BOOL g_trayShown = FALSE;   /* the tray icon is currently added         */
static char g_savedPath[MAX_PATH]; /* file path for the deferred save toast    */
static DWORD g_saveStartTick;      /* for the time-based save progress curve   */

/* A pending audio-file render, owned by the progress dialog and shared with the
 * background render thread.  The dialog frees it once the render reports back. */
typedef struct {
    SpeechEngine *engine;
    char         *text;            /* heap copy, freed by the dialog      */
    char          path[MAX_PATH];
    int           fmt;
    int           channels;
    BOOL          asXml;
    HWND          dlg;             /* progress dialog to notify when done */
} SaveReq;

static INT_PTR CALLBACK ProgressDlgProc(HWND, UINT, WPARAM, LPARAM);

/* Settings loaded from the registry at start-up. */
static int  g_haveSettings = 0;
static int  g_loadRate, g_loadPitch, g_loadVol;
static int  g_loadDark, g_loadFollowOs;
static char g_loadEngine[32];
static char g_loadVoice[256];
static BOOL g_dark     = FALSE;    /* dark theme active                   */
static BOOL g_followOs = FALSE;    /* follow the OS light/dark setting     */
static HBRUSH g_brBg   = NULL;     /* window background brush (dark)       */
static HBRUSH g_brCtl  = NULL;     /* control background brush (dark)      */
static char g_statusText[160];

/* ---- small helpers --------------------------------------------------- */

static void SetStatus(const char *text)
{
    if (text != g_statusText) lstrcpynA(g_statusText, text, sizeof(g_statusText));
    if (g_status) {
        /* In dark mode the part is owner-drawn so we can paint light text. */
        SendMessageA(g_status, SB_SETTEXTA,
                     (WPARAM)(g_dark ? SBT_OWNERDRAW : 0), (LPARAM)g_statusText);
    }
    /* The title bar stays a plain "Speakalive" - status lives only in the
     * status bar so it doesn't churn the window title. */
}

static void FormatSigned(int v, char *buf, int len)
{
    if (v > 0) { buf[0] = '+'; IntToStr(v, buf + 1, len - 1); }
    else IntToStr(v, buf, len);
}

static int TbPos(HWND tb) { return (int)SendMessageA(tb, TBM_GETPOS, 0, 0); }

static char *GetEditText(void)
{
    int len = GetWindowTextLengthA(g_text);
    char *buf = (char *)Mem_Alloc((SIZE_T)len + 1);
    if (!buf) return NULL;
    if (len) GetWindowTextA(g_text, buf, len + 1);
    buf[len] = 0;
    return buf;
}

/* ---- value labels ---------------------------------------------------- */

static void UpdateValueLabels(void)
{
    char b[16];
    FormatSigned(TbPos(g_rate) - RATE_DEF, b, sizeof(b));
    SetWindowTextA(g_rateVal, b);
    FormatSigned(TbPos(g_pitch) - PITCH_DEF, b, sizeof(b));
    SetWindowTextA(g_pitchVal, b);
    IntToStr(TbPos(g_volume), b, sizeof(b));
    lstrcatA(b, "%");
    SetWindowTextA(g_volVal, b);
}

static void ApplyAllSliders(void)
{
    if (!g_engine) return;
    if (g_engine->SetRate)   g_engine->SetRate(g_engine, TbPos(g_rate) - RATE_DEF);
    if (g_engine->SetPitch)  g_engine->SetPitch(g_engine, TbPos(g_pitch) - PITCH_DEF);
    if (g_engine->SetVolume) g_engine->SetVolume(g_engine, TbPos(g_volume));
    UpdateValueLabels();
}

/* ---- voices ---------------------------------------------------------- */

/* ---- friendly voice names ----
 * Users can give a voice a short custom name instead of the engine's long one
 * (e.g. "Adult Female #1, American English (TruVoice)").  Each is kept in the
 * registry keyed by the voice's ORIGINAL name, so it survives restarts and maps
 * back to the right voice regardless of list order. */
#define SA_VOICEKEY "Software\\Speakalive\\VoiceNames"

static void VoiceFriendlyGet(const char *orig, char *out, DWORD len)
{
    HKEY  k;
    DWORD sz = len, type = 0;
    out[0] = 0;
    if (RegOpenKeyExA(HKEY_CURRENT_USER, SA_VOICEKEY, 0, KEY_QUERY_VALUE, &k) == ERROR_SUCCESS) {
        if (RegQueryValueExA(k, orig, NULL, &type, (BYTE *)out, &sz) != ERROR_SUCCESS ||
            type != REG_SZ)
            out[0] = 0;
        RegCloseKey(k);
    }
    out[len - 1] = 0;
}

static void VoiceFriendlySet(const char *orig, const char *friendly)
{
    HKEY k;
    if (RegCreateKeyExA(HKEY_CURRENT_USER, SA_VOICEKEY, 0, NULL, 0,
                        KEY_SET_VALUE, NULL, &k, NULL) == ERROR_SUCCESS) {
        if (friendly && friendly[0])
            RegSetValueExA(k, orig, 0, REG_SZ, (const BYTE *)friendly,
                           (DWORD)lstrlenA(friendly) + 1);
        else
            RegDeleteValueA(k, orig);   /* blank -> revert to the original name */
        RegCloseKey(k);
    }
}

static void PopulateVoices(void)
{
    Voice *v = NULL;
    int n = 0, i;
    SendMessageA(g_voice, CB_RESETCONTENT, 0, 0);
    if (g_engine && g_engine->GetVoices) n = g_engine->GetVoices(g_engine, &v);
    /* The list is sorted alphabetically (CBS_SORT), so remember each item's
     * real engine index in its item data.  The text shown is the voice's
     * friendly name if one has been set, otherwise its original name. */
    for (i = 0; i < n; i++) {
        char disp[160];
        VoiceFriendlyGet(v[i].name, disp, sizeof(disp));
        if (disp[0] == 0) lstrcpynA(disp, v[i].name, sizeof(disp));
        {
            int pos = (int)SendMessageA(g_voice, CB_ADDSTRING, 0, (LPARAM)disp);
            if (pos >= 0) SendMessageA(g_voice, CB_SETITEMDATA, pos, (LPARAM)i);
        }
    }
    if (n > 0) {
        SendMessageA(g_voice, CB_SETCURSEL, 0, 0);
        if (g_engine->SetVoice)
            g_engine->SetVoice(g_engine,
                (int)SendMessageA(g_voice, CB_GETITEMDATA, 0, 0));
    }
    EnableWindow(g_voice, n > 0);
}

/* Select the combo item that maps to a given engine voice index (item data),
 * and tell the engine.  Used to keep a voice selected after it is renamed and
 * the list re-sorts. */
static void SelectVoiceByEngineIndex(int idx)
{
    int cnt = (int)SendMessageA(g_voice, CB_GETCOUNT, 0, 0), i;
    for (i = 0; i < cnt; i++) {
        if ((int)SendMessageA(g_voice, CB_GETITEMDATA, i, 0) == idx) {
            SendMessageA(g_voice, CB_SETCURSEL, i, 0);
            if (g_engine && g_engine->SetVoice) g_engine->SetVoice(g_engine, idx);
            return;
        }
    }
}

/* ---- engine switching ------------------------------------------------ */

static void SwitchEngine(int index)
{
    SpeechEngine *e;
    if (g_saving) return;          /* don't tear down the engine mid-render */
    e = Engines_Get(index);
    if (!e) return;

    /* Stop whatever the previous engine was doing. */
    if (g_engine && g_engine->Stop) g_engine->Stop(g_engine);
    g_speaking = g_paused = FALSE;

    if (e->Init && !e->Init(e)) {
        SetStatus("Engine failed to initialise");
        return;
    }
    g_engine = e;
    g_engineIndex = index;

    PopulateVoices();
    ApplyAllSliders();

    /* Volume only applies to engines that support it (SAPI 5). */
    EnableWindow(g_volume, e->supportsVolume);
    EnableWindow(g_volLbl, e->supportsVolume);
    EnableWindow(g_volVal, e->supportsVolume);
    EnableWindow(g_pitch,  e->supportsPitch);
    EnableWindow(g_pitchLbl, e->supportsPitch);
    EnableWindow(g_pitchVal, e->supportsPitch);

    {
        char s[80];
        lstrcpyA(s, "Engine: ");
        lstrcatA(s, e->display);
        SetStatus(s);
    }
}

/* ---- actions --------------------------------------------------------- */

/* Cycle to the next (dir=+1) or previous (dir=-1) engine tab, wrapping. */
static void CycleEngine(int dir)
{
    int n = Engines_Count();
    int sel;
    if (g_saving) return;
    if (n <= 1) return;
    sel = (int)SendMessageA(g_tab, TCM_GETCURSEL, 0, 0);
    sel = (sel + dir + n) % n;
    SendMessageA(g_tab, TCM_SETCURSEL, sel, 0);
    SwitchEngine(sel);   /* TCM_SETCURSEL does not raise TCN_SELCHANGE */
}

/* Best-effort well-formedness check of the XML/SSML the user typed, so a failed
 * speak can say SPECIFICALLY what is wrong (unclosed tag, mismatched tag, a '<'
 * where a '>' was meant, an unmatched quote) instead of a vague "check your
 * markup".  Returns NULL when it looks well-formed, else a message in g_mkMsg.
 * It checks structure, not the tag vocabulary - unknown tags still reach the
 * engine, which reports those separately. */
static char g_mkMsg[256];
static char g_mkStack[32][64];   /* names of currently-open tags */

static const char *CheckMarkup(const char *t)
{
    int depth = 0, i = 0;
    while (t[i]) {
        if (t[i] != '<') { i++; continue; }    /* a bare '>' is legal in content */

        /* Skip XML declarations <?...?> and comments / doctype <!...>. */
        if (t[i + 1] == '?' || t[i + 1] == '!') {
            i += 2;
            while (t[i] && t[i] != '>') i++;
            if (!t[i]) { lstrcpynA(g_mkMsg,
                "A '<?' or '<!' section was opened but never closed with '>'.",
                sizeof(g_mkMsg)); return g_mkMsg; }
            i++;
            continue;
        }
        /* '<' followed by a space or nothing is a literal less-than, not a tag. */
        if (t[i + 1] == ' ' || t[i + 1] == '\t' || t[i + 1] == '\r' ||
            t[i + 1] == '\n' || t[i + 1] == '>' || t[i + 1] == 0) {
            lstrcpynA(g_mkMsg, "A '<' is followed by a space or nothing, so it reads "
                "as a literal less-than sign. To speak a literal <, write it as &lt;.",
                sizeof(g_mkMsg));
            return g_mkMsg;
        }
        {
            int  isClose = (t[i + 1] == '/');
            char name[64];
            int  nl = 0, selfClose = 0;
            int  j = i + 1 + (isClose ? 1 : 0);
            char q = 0;                          /* open quote char, or 0 */

            while (t[j] == ' ' || t[j] == '\t') j++;
            while (t[j] && t[j] != ' ' && t[j] != '\t' && t[j] != '>' &&
                   t[j] != '/' && t[j] != '<' && t[j] != '\r' && t[j] != '\n') {
                if (nl < 63) name[nl++] = t[j];
                j++;
            }
            name[nl] = 0;
            if (nl == 0 && !isClose) {
                lstrcpynA(g_mkMsg, "A '<' is not followed by a tag name.", sizeof(g_mkMsg));
                return g_mkMsg;
            }
            /* Scan to the tag's '>', tracking quoted attribute values. */
            while (t[j]) {
                char c = t[j];
                if (q) { if (c == q) q = 0; j++; continue; }
                if (c == '"' || c == '\'') { q = c; j++; continue; }
                if (c == '<') {
                    wsprintfA(g_mkMsg, "Inside the tag <%s ...> there is a '<' before "
                        "the '>' that should close it. Did you mean '>', or is a '>' missing?", name);
                    return g_mkMsg;
                }
                if (c == '>') { if (t[j - 1] == '/') selfClose = 1; break; }
                j++;
            }
            if (!t[j]) {
                if (q) wsprintfA(g_mkMsg, "A quote mark is not matched in the tag <%s ...> - "
                                 "check for a missing or extra quote around an attribute value.", name);
                else   wsprintfA(g_mkMsg, "The tag <%s ...> was opened with '<' but never closed with '>'.", name);
                return g_mkMsg;
            }
            i = j + 1;
            if (isClose) {
                if (depth == 0) {
                    wsprintfA(g_mkMsg, "There is a closing tag </%s> with no matching opening tag before it.", name);
                    return g_mkMsg;
                }
                if (lstrcmpA(g_mkStack[depth - 1], name) != 0) {
                    wsprintfA(g_mkMsg, "The closing tag </%s> does not match the open tag <%s> - "
                              "tags must be closed in the order they were opened.", name, g_mkStack[depth - 1]);
                    return g_mkMsg;
                }
                depth--;
            } else if (!selfClose) {
                if (depth < 32) lstrcpynA(g_mkStack[depth++], name, 64);
            }
        }
    }
    if (depth > 0) {
        wsprintfA(g_mkMsg, "The tag <%s> was opened but never closed - add a matching </%s>.",
                  g_mkStack[depth - 1], g_mkStack[depth - 1]);
        return g_mkMsg;
    }
    return NULL;
}

/* Does the text actually contain a markup tag (an element, processing
 * instruction, or declaration)?  Used so a failed speak only blames the markup
 * when there is some - a plain sentence that a voice simply cannot say is a
 * voice problem, not a tag-support one, even with XML/SSML mode on. */
static BOOL TextHasMarkup(const char *t)
{
    const char *p;
    for (p = t; *p; p++) {
        if (p[0] == '<') {
            char c = p[1];
            if (c == '/' || c == '?' || c == '!' ||
                (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'))
                return TRUE;
        }
    }
    return FALSE;
}

static void DoSpeak(void)
{
    char *text;
    if (g_saving) return;
    if (!g_engine || !g_engine->Speak) { MessageBeep(MB_ICONWARNING); return; }
    text = GetEditText();
    if (!text || text[0] == 0) {
        SetStatus("Nothing to speak - type some text first");
        MessageBeep(MB_ICONASTERISK);
        Mem_Free(text);
        return;
    }
    /* With markup on, point out the exact syntax problem (announced) before the
     * engine just refuses the whole passage with a vague failure. */
    if (g_xmlMode) {
        const char *err = CheckMarkup(text);
        if (err) {
            SetStatus("Markup error");
            MessageBoxA(g_main, err, "Speakalive - markup error", MB_OK | MB_ICONWARNING);
            Mem_Free(text);
            return;
        }
    }
    if (g_engine->Speak(g_engine, text, g_xmlMode, g_main)) {
        g_speaking = TRUE; g_paused = FALSE;
        SetStatus("Speaking");
    } else {
        /* A bare error beep tells a screen-reader user nothing, so show an
         * announced message.  Only blame the markup when the text actually has
         * some (it already passed the syntax check above); a plain passage that
         * fails is a content/voice problem even with XML/SSML mode on. */
        SetStatus("Speech failed");
        MessageBoxA(g_main, (g_xmlMode && TextHasMarkup(text))
            ? "The text could not be spoken. The markup is well-formed, but a tag "
              "or value may not be supported by the selected voice."
            : "The text could not be spoken. The selected voice was unable to "
              "handle this text.",
            "Speakalive", MB_OK | MB_ICONWARNING);
    }
    Mem_Free(text);
}

static void DoPlayPause(void)
{
    if (g_saving) return;
    if (!g_engine) return;
    if (!g_speaking) { DoSpeak(); return; }
    if (!g_paused) {
        if (g_engine->Pause) g_engine->Pause(g_engine);
        g_paused = TRUE; SetStatus("Paused");
    } else {
        if (g_engine->Resume) g_engine->Resume(g_engine);
        g_paused = FALSE; SetStatus("Speaking");
    }
}

static void DoStop(void)
{
    if (g_saving) return;
    if (g_engine && g_engine->Stop) g_engine->Stop(g_engine);
    g_speaking = g_paused = FALSE;
    SetStatus("Stopped");
}

static void DoReset(void)
{
    if (g_saving) return;
    SendMessageA(g_rate,   TBM_SETPOS, TRUE, RATE_DEF);
    SendMessageA(g_pitch,  TBM_SETPOS, TRUE, PITCH_DEF);
    SendMessageA(g_volume, TBM_SETPOS, TRUE, VOL_DEF);
    ApplyAllSliders();
    SetStatus("Sliders reset to default");
}

/* Background render thread: synthesise the whole text to the audio file, then
 * tell the progress dialog (which owns the request) how it went. */
static DWORD WINAPI SaveThreadProc(LPVOID param)
{
    SaveReq *r = (SaveReq *)param;
    BOOL ok;
    CoInitializeEx(NULL, COINIT_APARTMENTTHREADED);
    ok = r->engine->SaveToFile(r->engine, r->text, r->asXml,
                               r->path, r->fmt, r->channels);
    CoUninitialize();
    PostMessageA(r->dlg, WM_SA_SAVEDONE, (WPARAM)ok, (LPARAM)r->fmt);
    return 0;   /* the dialog frees the request */
}

static void DoSave(void)
{
    OPENFILENAMEA ofn;
    char file[MAX_PATH];
    char *text;
    SaveReq *req;
    int  fmt, channels, n;

    if (g_saving) return;
    channels = g_stereo ? 2 : 1;   /* from the File menu toggle, not a prompt */
    if (!g_engine || !g_engine->SaveToFile) {
        MessageBoxA(g_main, "Saving to a file is not supported for this engine.",
                    APP_TITLE, MB_OK | MB_ICONINFORMATION);
        return;
    }
    text = GetEditText();
    if (!text || text[0] == 0) {
        MessageBoxA(g_main, "Type some text to save first.", APP_TITLE,
                    MB_OK | MB_ICONINFORMATION);
        Mem_Free(text);
        return;
    }

    file[0] = 0;
    ZeroMemory(&ofn, sizeof(ofn));
    ofn.lStructSize = sizeof(ofn);
    ofn.hwndOwner   = g_main;
    ofn.lpstrFilter = "Wave audio (*.wav)\0*.wav\0MP3 audio (*.mp3)\0*.mp3\0";
    ofn.nFilterIndex= 1;
    ofn.lpstrFile   = file;
    ofn.nMaxFile    = MAX_PATH;
    ofn.lpstrTitle  = "Save spoken audio";
    ofn.lpstrDefExt = "wav";
    ofn.Flags = OFN_OVERWRITEPROMPT | OFN_HIDEREADONLY | OFN_PATHMUSTEXIST |
                OFN_NOCHANGEDIR;
    if (!GetSaveFileNameA(&ofn)) { Mem_Free(text); return; }

    /* Format from filter index, overridden by an explicit .mp3 extension. */
    fmt = (ofn.nFilterIndex == 2) ? FMT_MP3 : FMT_WAV;
    n = lstrlenA(file);
    if (n > 4) {
        const char *ext = file + n - 4;
        if (lstrcmpiA(ext, ".mp3") == 0) fmt = FMT_MP3;
        else if (lstrcmpiA(ext, ".wav") == 0) fmt = FMT_WAV;
    }

    req = (SaveReq *)Mem_Alloc(sizeof(SaveReq));
    if (!req) { Mem_Free(text); return; }
    req->engine   = g_engine;
    req->text     = text;          /* ownership passes to the dialog */
    req->fmt      = fmt;
    req->channels = channels;
    req->asXml    = g_xmlMode;
    req->dlg      = NULL;
    lstrcpynA(req->path, file, MAX_PATH);

    /* A MODELESS progress dialog drives the render: the main window stays
     * enabled (so a screen reader can still read it) and Cancel can abort.  The
     * dialog owns the request, reports completion via WM_SA_SAVEDONE, and frees
     * everything itself - so DoSave returns immediately here. */
    g_saveCancel = 0;
    g_saving = TRUE;
    SetStatus("Saving audio...");
    g_progressDlg = CreateDialogParamA(g_inst, MAKEINTRESOURCEA(IDD_PROGRESS),
                                       g_main, ProgressDlgProc, (LPARAM)req);
    if (!g_progressDlg) {
        /* Could not create the dialog - render inline as a last resort. */
        BOOL ok = g_engine->SaveToFile(req->engine, req->text, req->asXml,
                                       req->path, req->fmt, req->channels);
        g_saving = FALSE;
        Mem_Free(req->text);
        Mem_Free(req);
        if (ok) {
            SetStatus("Audio saved");
            MessageBoxA(g_main, "Audio file saved successfully.", APP_TITLE,
                        MB_OK | MB_ICONINFORMATION);
        } else {
            SetStatus("Save failed");
            MessageBoxA(g_main, "Could not save the audio file.", APP_TITLE,
                        MB_OK | MB_ICONERROR);
        }
    }
}

static void DoSaveText(void)
{
    OPENFILENAMEA ofn;
    char  file[MAX_PATH];
    char *text;
    HANDLE h;
    DWORD  written;
    int    n;

    if (g_saving) return;
    text = GetEditText();

    file[0] = 0;
    ZeroMemory(&ofn, sizeof(ofn));
    ofn.lStructSize = sizeof(ofn);
    ofn.hwndOwner   = g_main;
    ofn.lpstrFilter = "Text files (*.txt)\0*.txt\0All files (*.*)\0*.*\0";
    ofn.nFilterIndex= 1;
    ofn.lpstrFile   = file;
    ofn.nMaxFile    = MAX_PATH;
    ofn.lpstrTitle  = "Save text";
    ofn.lpstrDefExt = "txt";
    ofn.Flags = OFN_OVERWRITEPROMPT | OFN_HIDEREADONLY | OFN_PATHMUSTEXIST |
                OFN_NOCHANGEDIR;
    if (!GetSaveFileNameA(&ofn)) { Mem_Free(text); return; }

    h = CreateFileA(file, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS,
                    FILE_ATTRIBUTE_NORMAL, NULL);
    if (h != INVALID_HANDLE_VALUE) {
        n = text ? lstrlenA(text) : 0;
        if (n) WriteFile(h, text, (DWORD)n, &written, NULL);
        CloseHandle(h);
        SetStatus("Text saved");
        g_modified = FALSE;     /* the text is now safely on disk */
    } else {
        SetStatus("Could not save text");
        MessageBoxA(g_main, "Could not save the text file.", APP_TITLE,
                    MB_OK | MB_ICONERROR);
    }
    Mem_Free(text);
}

/* ---- read a web page ------------------------------------------------- */

/* Defined later (dark-mode section); the URL dialog reuses them. */
static void DrawButton(const DRAWITEMSTRUCT *di);
static void SetTitleBarDark(HWND h, BOOL on);

static INT_PTR CALLBACK UrlDlgProc(HWND dlg, UINT msg, WPARAM wp, LPARAM lp)
{
    switch (msg) {
    case WM_INITDIALOG:
        SetWindowLongPtrA(dlg, DWLP_USER, (LONG_PTR)lp);  /* output buffer */
        SendMessageA(dlg, DM_SETDEFID, IDOK, 0);          /* Enter = OK     */
        SetTitleBarDark(dlg, g_dark);
        SetFocus(GetDlgItem(dlg, IDC_URLEDIT));
        return FALSE;

    /* Apply the program's dark theme to the dialog. */
    case WM_CTLCOLORDLG:
    case WM_CTLCOLORSTATIC:
    case WM_CTLCOLORBTN:
        if (g_dark) {
            SetTextColor((HDC)wp, DARK_TXT);
            SetBkColor((HDC)wp, DARK_BG);
            return (INT_PTR)g_brBg;
        }
        break;
    case WM_CTLCOLOREDIT:
        if (g_dark) {
            SetTextColor((HDC)wp, DARK_TXT);
            SetBkColor((HDC)wp, DARK_CTL);
            return (INT_PTR)g_brCtl;
        }
        break;
    case WM_DRAWITEM:
        DrawButton((const DRAWITEMSTRUCT *)lp);
        return TRUE;

    case WM_COMMAND:
        if (LOWORD(wp) == IDOK) {
            char *buf = (char *)(LONG_PTR)GetWindowLongPtrA(dlg, DWLP_USER);
            if (buf) GetDlgItemTextA(dlg, IDC_URLEDIT, buf, 2048);
            EndDialog(dlg, IDOK);
            return TRUE;
        }
        if (LOWORD(wp) == IDCANCEL) { EndDialog(dlg, IDCANCEL); return TRUE; }
        break;
    }
    return FALSE;
}

/* "Rename Voice" dialog: edit pre-filled with the current friendly name (blank
 * if none), caption naming the voice.  buf is in/out. */
typedef struct { const char *orig; char *buf; int len; } RenameCtx;

static INT_PTR CALLBACK RenameDlgProc(HWND dlg, UINT msg, WPARAM wp, LPARAM lp)
{
    RenameCtx *ctx;
    switch (msg) {
    case WM_INITDIALOG: {
        char cap[300];
        SetWindowLongPtrA(dlg, DWLP_USER, (LONG_PTR)lp);
        ctx = (RenameCtx *)(LONG_PTR)lp;
        wsprintfA(cap, "Rename voice: %s", ctx->orig);
        SetWindowTextA(dlg, cap);
        SetDlgItemTextA(dlg, IDC_RENAMEEDIT, ctx->buf);
        SendDlgItemMessageA(dlg, IDC_RENAMEEDIT, EM_SETSEL, 0, -1);  /* select all */
        SendMessageA(dlg, DM_SETDEFID, IDOK, 0);
        SetTitleBarDark(dlg, g_dark);
        SetFocus(GetDlgItem(dlg, IDC_RENAMEEDIT));
        return FALSE;
    }
    case WM_CTLCOLORDLG:
    case WM_CTLCOLORSTATIC:
    case WM_CTLCOLORBTN:
        if (g_dark) {
            SetTextColor((HDC)wp, DARK_TXT);
            SetBkColor((HDC)wp, DARK_BG);
            return (INT_PTR)g_brBg;
        }
        break;
    case WM_CTLCOLOREDIT:
        if (g_dark) {
            SetTextColor((HDC)wp, DARK_TXT);
            SetBkColor((HDC)wp, DARK_CTL);
            return (INT_PTR)g_brCtl;
        }
        break;
    case WM_DRAWITEM:
        DrawButton((const DRAWITEMSTRUCT *)lp);
        return TRUE;

    case WM_COMMAND:
        if (LOWORD(wp) == IDOK) {
            ctx = (RenameCtx *)(LONG_PTR)GetWindowLongPtrA(dlg, DWLP_USER);
            if (ctx) GetDlgItemTextA(dlg, IDC_RENAMEEDIT, ctx->buf, ctx->len);
            EndDialog(dlg, IDOK);
            return TRUE;
        }
        if (LOWORD(wp) == IDCANCEL) { EndDialog(dlg, IDCANCEL); return TRUE; }
        break;
    }
    return FALSE;
}

/* Give the currently-selected voice a friendly display name (or clear it). */
static void DoRenameVoice(void)
{
    Voice *v = NULL;
    int    n, sel, idx;
    char   orig[256], friendly[128];
    RenameCtx ctx;

    if (g_saving) return;
    if (!g_engine || !g_engine->GetVoices) { MessageBeep(MB_ICONWARNING); return; }
    sel = (int)SendMessageA(g_voice, CB_GETCURSEL, 0, 0);
    if (sel < 0) { SetStatus("Select a voice to rename first"); MessageBeep(MB_ICONASTERISK); return; }
    idx = (int)SendMessageA(g_voice, CB_GETITEMDATA, sel, 0);
    n = g_engine->GetVoices(g_engine, &v);
    if (idx < 0 || idx >= n) return;
    lstrcpynA(orig, v[idx].name, sizeof(orig));

    VoiceFriendlyGet(orig, friendly, sizeof(friendly));   /* pre-fill current name */
    ctx.orig = orig; ctx.buf = friendly; ctx.len = (int)sizeof(friendly);
    if (DialogBoxParamA(g_inst, MAKEINTRESOURCEA(IDD_RENAME), g_main,
                        RenameDlgProc, (LPARAM)&ctx) != IDOK)
        return;

    VoiceFriendlySet(orig, friendly);   /* save, or clear when left blank */
    PopulateVoices();                   /* re-list (name change re-sorts it) */
    SelectVoiceByEngineIndex(idx);      /* keep this voice selected */
    SetStatus(friendly[0] ? "Voice renamed" : "Voice name reset to original");
}

/* ---- back up / restore custom voice names ----------------------------------
 * The friendly names live under HKCU\Software\Speakalive\VoiceNames, one value
 * per renamed voice (value name = original voice name, value data = friendly
 * name).  Back Up writes them all to a small text file; Restore reads such a
 * file back into the registry, merging - existing names are updated and any not
 * mentioned in the file are left alone.  This lets a collection of names survive
 * a Windows reinstall or a move to a new PC.  The file is one header line then
 * one TAB-separated line per name:  <original name><TAB><friendly name>.  Voice
 * names never contain a tab or a line break, so the format needs no escaping. */
#define SA_VNBACKUP_TAG "Speakalive Voice Names"
#define SA_VNBACKUP_HDR SA_VNBACKUP_TAG " 1"

static void DoBackupVoiceNames(void)
{
    OPENFILENAMEA ofn;
    char   file[MAX_PATH];
    HKEY   k = NULL;
    HANDLE h;
    DWORD  i, written, count = 0, values = 0;
    char   line[1024];

    /* Nothing to do if there are no custom names - say so up front rather than
     * popping a Save dialog that would write an empty file. */
    if (RegOpenKeyExA(HKEY_CURRENT_USER, SA_VOICEKEY, 0, KEY_QUERY_VALUE, &k)
            != ERROR_SUCCESS ||
        RegQueryInfoKeyA(k, NULL, NULL, NULL, NULL, NULL, NULL, &values,
                         NULL, NULL, NULL, NULL) != ERROR_SUCCESS ||
        values == 0) {
        if (k) RegCloseKey(k);
        SetStatus("No custom voice names to back up");
        MessageBoxA(g_main, "There are no custom voice names to back up yet. "
                    "Rename a voice first (Speech then Rename Voice).",
                    APP_TITLE, MB_OK | MB_ICONINFORMATION);
        return;
    }

    lstrcpynA(file, "Speakalive voice names.savn", sizeof(file));
    ZeroMemory(&ofn, sizeof(ofn));
    ofn.lStructSize = sizeof(ofn);
    ofn.hwndOwner   = g_main;
    ofn.lpstrFilter = "Speakalive voice names (*.savn)\0*.savn\0All files (*.*)\0*.*\0";
    ofn.nFilterIndex= 1;
    ofn.lpstrFile   = file;
    ofn.nMaxFile    = MAX_PATH;
    ofn.lpstrTitle  = "Back up voice names";
    ofn.lpstrDefExt = "savn";
    ofn.Flags = OFN_OVERWRITEPROMPT | OFN_HIDEREADONLY | OFN_PATHMUSTEXIST |
                OFN_NOCHANGEDIR;
    if (!GetSaveFileNameA(&ofn)) { RegCloseKey(k); return; }

    h = CreateFileA(file, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS,
                    FILE_ATTRIBUTE_NORMAL, NULL);
    if (h == INVALID_HANDLE_VALUE) {
        RegCloseKey(k);
        SetStatus("Could not save the backup");
        MessageBoxA(g_main, "Could not write the backup file.", APP_TITLE,
                    MB_OK | MB_ICONERROR);
        return;
    }

    WriteFile(h, SA_VNBACKUP_HDR "\r\n",
              (DWORD)lstrlenA(SA_VNBACKUP_HDR "\r\n"), &written, NULL);

    for (i = 0; ; i++) {
        char  name[512], data[256];
        DWORD nameLen = sizeof(name), dataLen = sizeof(data), type = 0;
        LONG  r;
        r = RegEnumValueA(k, i, name, &nameLen, NULL, &type,
                          (BYTE *)data, &dataLen);
        if (r == ERROR_NO_MORE_ITEMS) break;
        if (r != ERROR_SUCCESS) continue;          /* skip an oversized entry */
        if (type != REG_SZ || name[0] == 0) continue;
        data[sizeof(data) - 1] = 0;
        if (data[0] == 0) continue;
        wsprintfA(line, "%s\t%s\r\n", name, data);
        WriteFile(h, line, (DWORD)lstrlenA(line), &written, NULL);
        count++;
    }
    CloseHandle(h);
    RegCloseKey(k);

    if (count == 0) {
        SetStatus("No custom voice names to back up");
        MessageBoxA(g_main, "There are no custom voice names to back up yet. "
                    "Rename a voice first (Speech then Rename Voice).",
                    APP_TITLE, MB_OK | MB_ICONINFORMATION);
    } else {
        char msg[128];
        wsprintfA(msg, "Backed up %lu voice name%s.",
                  (unsigned long)count, count == 1 ? "" : "s");
        SetStatus("Voice names backed up");
        MessageBoxA(g_main, msg, APP_TITLE, MB_OK | MB_ICONINFORMATION);
    }
}

static void DoRestoreVoiceNames(void)
{
    OPENFILENAMEA ofn;
    char   file[MAX_PATH];
    HANDLE h;
    DWORD  size, read = 0, taglen;
    char  *buf, *p, *limit;
    int    sel, keepIdx = -1, count = 0;

    file[0] = 0;
    ZeroMemory(&ofn, sizeof(ofn));
    ofn.lStructSize = sizeof(ofn);
    ofn.hwndOwner   = g_main;
    ofn.lpstrFilter = "Speakalive voice names (*.savn)\0*.savn\0All files (*.*)\0*.*\0";
    ofn.nFilterIndex= 1;
    ofn.lpstrFile   = file;
    ofn.nMaxFile    = MAX_PATH;
    ofn.lpstrTitle  = "Restore voice names";
    ofn.lpstrDefExt = "savn";
    ofn.Flags = OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST | OFN_HIDEREADONLY |
                OFN_NOCHANGEDIR;
    if (!GetOpenFileNameA(&ofn)) return;

    h = CreateFileA(file, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING,
                    FILE_ATTRIBUTE_NORMAL, NULL);
    if (h == INVALID_HANDLE_VALUE) {
        SetStatus("Could not open the backup");
        MessageBoxA(g_main, "Could not open the backup file.", APP_TITLE,
                    MB_OK | MB_ICONERROR);
        return;
    }
    size = GetFileSize(h, NULL);
    if (size == INVALID_FILE_SIZE || size == 0 || size > 0x100000) {  /* 1 MB cap */
        CloseHandle(h);
        SetStatus("Not a valid backup file");
        MessageBoxA(g_main, "That file is empty or too large to be a voice-names "
                    "backup.", APP_TITLE, MB_OK | MB_ICONWARNING);
        return;
    }
    buf = (char *)Mem_Alloc((SIZE_T)size + 1);
    if (!buf) { CloseHandle(h); return; }
    if (!ReadFile(h, buf, size, &read, NULL)) read = 0;
    CloseHandle(h);
    buf[read] = 0;

    /* The file must start with our tag, otherwise it is not our backup. */
    taglen = (DWORD)lstrlenA(SA_VNBACKUP_TAG);
    if (read < taglen || memcmp(buf, SA_VNBACKUP_TAG, taglen) != 0) {
        Mem_Free(buf);
        SetStatus("Not a Speakalive voice-names backup");
        MessageBoxA(g_main, "That file is not a Speakalive voice-names backup.",
                    APP_TITLE, MB_OK | MB_ICONWARNING);
        return;
    }

    p = buf;
    limit = buf + read;
    while (p < limit && *p != '\n') p++;   /* skip the header line */
    if (p < limit) p++;

    /* Each remaining line: <original><TAB><friendly>. */
    while (p < limit) {
        char *ls = p, *le, *tab;
        while (p < limit && *p != '\n') p++;
        le = p;
        if (p < limit) p++;                       /* step past '\n' */
        if (le > ls && le[-1] == '\r') le--;      /* drop a trailing CR */
        *le = 0;                                   /* terminate this line */
        for (tab = ls; tab < le && *tab != '\t'; tab++) ;
        if (tab < le) {
            *tab = 0;                              /* split original / friendly */
            if (ls[0] && tab[1]) {
                VoiceFriendlySet(ls, tab + 1);
                count++;
            }
        }
    }
    Mem_Free(buf);

    /* Refresh the list so restored names appear, keeping the current voice. */
    sel = (int)SendMessageA(g_voice, CB_GETCURSEL, 0, 0);
    if (sel >= 0) keepIdx = (int)SendMessageA(g_voice, CB_GETITEMDATA, sel, 0);
    PopulateVoices();
    if (keepIdx >= 0) SelectVoiceByEngineIndex(keepIdx);

    if (count > 0) {
        char msg[192];
        wsprintfA(msg, "Restored %d voice name%s. Names for voices that are not "
                  "installed here are kept for when they are.",
                  count, count == 1 ? "" : "s");
        SetStatus("Voice names restored");
        MessageBoxA(g_main, msg, APP_TITLE, MB_OK | MB_ICONINFORMATION);
    } else {
        SetStatus("No voice names in that file");
        MessageBoxA(g_main, "That backup did not contain any voice names.",
                    APP_TITLE, MB_OK | MB_ICONWARNING);
    }
}

/* ---- available markup tags ------------------------------------------------
 * A reference list of the control tags / markup each engine understands, shown
 * in a list view from which the user can copy a tag with Control + C and paste
 * it into their text.  The sample values in each tag are just illustrative; the
 * user edits them after pasting.  Support varies a little from voice to voice. */
typedef struct { const char *tag; const char *desc; } TagInfo;

/* SAPI 4 uses backslash control tags embedded in the text. */
static const TagInfo g_tagsSapi4[] = {
    { "\\Spd=150\\",      "Set the speaking speed in words per minute." },
    { "\\Pit=100\\",      "Set the baseline pitch in hertz." },
    { "\\Vol=65535\\",    "Set the volume, from 0 (silent) to 65535 (loudest)." },
    { "\\Pau=500\\",      "Pause for the given number of milliseconds." },
    { "\\Rst\\",          "Reset speed, pitch and volume to the voice's defaults." },
    { "\\Mrk=1\\",        "Place a numbered bookmark at this point in the text." },
    { "\\Chr=\"Normal\"\\", "Set the voice's character or style, e.g. Normal or Monotone." },
    { "\\Emp\\",          "Emphasise the word that follows." },
};

/* SAPI 5 uses Microsoft's XML TTS tags. */
static const TagInfo g_tagsSapi5[] = {
    { "<rate speed=\"-3\"/>",       "Change the speed, from -10 (slowest) to 10 (fastest)." },
    { "<rate absspeed=\"0\"/>",     "Set the absolute speed, from -10 to 10." },
    { "<pitch middle=\"3\"/>",      "Change the pitch, from -10 (lowest) to 10 (highest)." },
    { "<volume level=\"80\"/>",     "Set the volume, from 0 to 100." },
    { "<emph>word</emph>",          "Emphasise the enclosed words." },
    { "<silence msec=\"500\"/>",    "Insert the given number of milliseconds of silence." },
    { "<spell>text</spell>",        "Speak the enclosed text one letter at a time." },
    { "<bookmark mark=\"name\"/>",  "Insert a named bookmark at this point." },
    { "<pron sym=\"h eh l ow\"/>",  "Speak using the given phoneme symbols." },
    { "<voice required=\"Name=Microsoft Mary\">text</voice>", "Speak the enclosed text in another voice." },
};

/* OneCore uses W3C SSML. */
static const TagInfo g_tagsOnecore[] = {
    { "<speak version=\"1.0\" xml:lang=\"en-US\">text</speak>", "Wrap the whole document (required for SSML)." },
    { "<prosody rate=\"slow\" pitch=\"+2st\" volume=\"loud\">text</prosody>", "Change rate, pitch and/or volume." },
    { "<break time=\"500ms\"/>",    "Pause for the given length of time." },
    { "<emphasis level=\"strong\">text</emphasis>", "Emphasise the enclosed text." },
    { "<say-as interpret-as=\"characters\">text</say-as>", "Control how text is read, e.g. characters, digits or date." },
    { "<voice name=\"Microsoft Zira\">text</voice>", "Speak the enclosed text in another voice." },
    { "<phoneme alphabet=\"ipa\" ph=\"...\">text</phoneme>", "Pronounce the text using the given phonemes." },
    { "<sub alias=\"World Wide Web\">WWW</sub>", "Speak a substitute for the written text." },
    { "<p>text</p>",                "Mark a paragraph." },
    { "<s>text</s>",                "Mark a sentence." },
};

typedef struct { const TagInfo *tags; int count; const char *title; } TagsCtx;

/* Put a string on the clipboard as plain text. */
static void ClipboardSetText(HWND owner, const char *s)
{
    SIZE_T  len = (SIZE_T)lstrlenA(s) + 1;
    HGLOBAL hg;
    if (!OpenClipboard(owner)) return;
    EmptyClipboard();
    hg = GlobalAlloc(GMEM_MOVEABLE, len);
    if (hg) {
        char *p = (char *)GlobalLock(hg);
        if (p) {
            lstrcpynA(p, s, (int)len);
            GlobalUnlock(hg);
            SetClipboardData(CF_TEXT, hg);
        } else {
            GlobalFree(hg);
        }
    }
    CloseClipboard();
}

/* Copy the Tag column of every selected list row, one per line. */
static void CopySelectedTags(HWND list)
{
    char buf[2048], item[256];
    int  used = 0, i = -1, any = 0;
    buf[0] = 0;
    for (;;) {
        int l;
        i = ListView_GetNextItem(list, i, LVNI_SELECTED);
        if (i < 0) break;
        item[0] = 0;
        ListView_GetItemText(list, i, 0, item, sizeof(item));
        if (any && used + 2 < (int)sizeof(buf)) {
            buf[used++] = '\r'; buf[used++] = '\n'; buf[used] = 0;
        }
        l = lstrlenA(item);
        if (used + l < (int)sizeof(buf)) {
            lstrcpynA(buf + used, item, (int)sizeof(buf) - used);
            used += l;
        }
        any = 1;
    }
    if (any) ClipboardSetText(list, buf);
}

/* In dark mode the list's column-header strip is a separate control that ignores
 * the list's colours and would stay system-light.  We subclass the list so we
 * receive the header's NM_CUSTOMDRAW (it is sent to the header's parent, the
 * list, not the dialog) and paint the header dark ourselves.  Only installed
 * when dark, so it always draws dark.  The original proc is kept in the list's
 * GWLP_USERDATA. */
static LRESULT CALLBACK TagsListProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    WNDPROC orig = (WNDPROC)(LONG_PTR)GetWindowLongPtrA(hwnd, GWLP_USERDATA);
    if (msg == WM_NOTIFY) {
        NMHDR *nh = (NMHDR *)lp;
        /* Only the header's custom draw - not, say, the label-tip tooltip's. */
        if (nh->code == NM_CUSTOMDRAW && nh->hwndFrom == ListView_GetHeader(hwnd)) {
            NMCUSTOMDRAW *cd = (NMCUSTOMDRAW *)lp;
            if (cd->dwDrawStage == CDDS_PREPAINT) {
                FillRect(cd->hdc, &cd->rc, g_brBg);   /* base + any gap past the last column */
                return CDRF_NOTIFYITEMDRAW;
            }
            if (cd->dwDrawStage == CDDS_ITEMPREPAINT) {
                HDC     dc = cd->hdc;
                RECT    rc = cd->rc, div;
                HBRUSH  divb = CreateSolidBrush(RGB(70, 70, 70));
                HDITEMA hi;
                char    text[128];
                FillRect(dc, &rc, g_brBg);
                div = rc; div.left = div.right  - 1; FillRect(dc, &div, divb);  /* column divider */
                div = rc; div.top  = div.bottom - 1; FillRect(dc, &div, divb);  /* base line      */
                DeleteObject(divb);
                text[0] = 0;
                ZeroMemory(&hi, sizeof(hi));
                hi.mask = HDI_TEXT; hi.pszText = text; hi.cchTextMax = sizeof(text);
                SendMessageA(nh->hwndFrom, HDM_GETITEMA, cd->dwItemSpec, (LPARAM)&hi);
                SetBkMode(dc, TRANSPARENT);
                SetTextColor(dc, DARK_TXT);
                rc.left += 6; rc.right -= 4;
                DrawTextA(dc, text, -1, &rc,
                          DT_LEFT | DT_VCENTER | DT_SINGLELINE | DT_END_ELLIPSIS | DT_NOPREFIX);
                return CDRF_SKIPDEFAULT;
            }
            return CDRF_DODEFAULT;
        }
    } else if (msg == WM_NCDESTROY) {
        SetWindowLongPtrA(hwnd, GWLP_WNDPROC, (LONG_PTR)orig);   /* unhook */
    }
    return CallWindowProcA(orig, hwnd, msg, wp, lp);
}

static INT_PTR CALLBACK TagsDlgProc(HWND dlg, UINT msg, WPARAM wp, LPARAM lp)
{
    switch (msg) {
    case WM_INITDIALOG: {
        TagsCtx *c   = (TagsCtx *)lp;
        HWND     list = GetDlgItem(dlg, IDC_TAGLIST);
        LVCOLUMNA col;
        int i;

        if (c->title) SetWindowTextA(dlg, c->title);
        ListView_SetExtendedListViewStyle(list, LVS_EX_FULLROWSELECT | LVS_EX_LABELTIP);

        ZeroMemory(&col, sizeof(col));
        col.mask     = LVCF_TEXT | LVCF_WIDTH | LVCF_SUBITEM;
        col.cx       = 175; col.iSubItem = 0; col.pszText = "Tag";
        ListView_InsertColumn(list, 0, &col);
        col.cx       = 320; col.iSubItem = 1; col.pszText = "What it does";
        ListView_InsertColumn(list, 1, &col);

        for (i = 0; i < c->count; i++) {
            LVITEMA it;
            ZeroMemory(&it, sizeof(it));
            it.mask = LVIF_TEXT; it.iItem = i; it.iSubItem = 0;
            it.pszText = (char *)c->tags[i].tag;
            ListView_InsertItem(list, &it);
            ListView_SetItemText(list, i, 1, (char *)c->tags[i].desc);
        }

        if (g_dark) {
            WNDPROC origProc;
            ListView_SetBkColor(list, DARK_CTL);
            ListView_SetTextBkColor(list, DARK_CTL);
            ListView_SetTextColor(list, DARK_TXT);
            /* Hand-draw the column header dark (see TagsListProc). */
            origProc = (WNDPROC)(LONG_PTR)SetWindowLongPtrA(list, GWLP_WNDPROC,
                                                            (LONG_PTR)TagsListProc);
            SetWindowLongPtrA(list, GWLP_USERDATA, (LONG_PTR)origProc);
            InvalidateRect(ListView_GetHeader(list), NULL, TRUE);
        }
        ListView_SetItemState(list, 0, LVIS_SELECTED | LVIS_FOCUSED,
                              LVIS_SELECTED | LVIS_FOCUSED);
        SetTitleBarDark(dlg, g_dark);
        SetFocus(list);
        return FALSE;
    }

    case WM_CTLCOLORDLG:
    case WM_CTLCOLORSTATIC:
    case WM_CTLCOLORBTN:
        if (g_dark) {
            SetTextColor((HDC)wp, DARK_TXT);
            SetBkColor((HDC)wp, DARK_BG);
            return (INT_PTR)g_brBg;
        }
        break;
    case WM_DRAWITEM:
        DrawButton((const DRAWITEMSTRUCT *)lp);
        return TRUE;

    case WM_NOTIFY: {
        NMHDR *nh = (NMHDR *)lp;
        if (nh->idFrom == IDC_TAGLIST && nh->code == LVN_KEYDOWN) {
            NMLVKEYDOWN *kd = (NMLVKEYDOWN *)lp;
            if (kd->wVKey == 'C' && (GetKeyState(VK_CONTROL) & 0x8000))
                CopySelectedTags(nh->hwndFrom);
        }
        break;
    }

    case WM_COMMAND:
        if (LOWORD(wp) == IDOK || LOWORD(wp) == IDCANCEL) {
            EndDialog(dlg, LOWORD(wp));
            return TRUE;
        }
        break;
    }
    return FALSE;
}

/* Show the markup-tag reference for the engine that is currently selected. */
static void DoShowTags(void)
{
    TagsCtx ctx;
    char    title[80];
    if (!g_engine) { MessageBeep(MB_ICONASTERISK); return; }

    if (lstrcmpA(g_engine->id, "sapi4") == 0) {
        ctx.tags = g_tagsSapi4; ctx.count = (int)(sizeof(g_tagsSapi4) / sizeof(g_tagsSapi4[0]));
    } else if (lstrcmpA(g_engine->id, "onecore") == 0) {
        ctx.tags = g_tagsOnecore; ctx.count = (int)(sizeof(g_tagsOnecore) / sizeof(g_tagsOnecore[0]));
    } else {   /* SAPI 5 (and any future XML engine) */
        ctx.tags = g_tagsSapi5; ctx.count = (int)(sizeof(g_tagsSapi5) / sizeof(g_tagsSapi5[0]));
    }
    wsprintfA(title, "%s markup tags", g_engine->display);
    ctx.title = title;
    DialogBoxParamA(g_inst, MAKEINTRESOURCEA(IDD_TAGS), g_main, TagsDlgProc, (LPARAM)&ctx);
}

/* Remove the transient save-notification tray icon if it is showing. */
static void RemoveTrayIcon(void)
{
    if (g_trayShown) {
        KillTimer(g_main, TIMER_TRAY);
        Shell_NotifyIconA(NIM_DELETE, &g_nid);
        g_trayShown = FALSE;
    }
}

/* Announce a successful save without a modal dialog.  We add a notification-
 * area icon and fire a balloon: the shell shows it as a toast on Windows 8+ and
 * as a classic balloon on Windows 7 down to 2000.  The icon removes itself when
 * the balloon is dismissed (WM_SA_TRAY) or after TRAY_MS as a backstop. */
static void ShowSaveNotification(const char *path)
{
    const char *fn = path, *p;
    char info[300];

    for (p = path; *p; p++) if (*p == '\\' || *p == '/') fn = p + 1;
    wsprintfA(info, "Audio saved: %s", fn);

    ZeroMemory(&g_nid, sizeof(g_nid));
    /* Built with _WIN32_WINNT=0x0500, so NOTIFYICONDATAA is the Win2000 (V2)
     * layout - sizeof is the balloon-capable V2 size the shell expects. */
    g_nid.cbSize           = sizeof(g_nid);
    g_nid.hWnd             = g_main;
    g_nid.uID              = 1;
    g_nid.uFlags           = NIF_ICON | NIF_MESSAGE | NIF_TIP;
    g_nid.uCallbackMessage = WM_SA_TRAY;
    g_nid.hIcon            = LoadIconA(NULL, (LPCSTR)IDI_APPLICATION);
    lstrcpynA(g_nid.szTip, APP_TITLE, sizeof(g_nid.szTip));

    if (!g_trayShown) {
        if (!Shell_NotifyIconA(NIM_ADD, &g_nid)) return;   /* no shell tray */
        g_trayShown = TRUE;
    }

    g_nid.uFlags      = NIF_INFO;
    g_nid.dwInfoFlags = NIIF_INFO;
    lstrcpynA(g_nid.szInfoTitle, APP_TITLE, sizeof(g_nid.szInfoTitle));
    lstrcpynA(g_nid.szInfo, info, sizeof(g_nid.szInfo));
    Shell_NotifyIconA(NIM_MODIFY, &g_nid);

    SetTimer(g_main, TIMER_TRAY, TRAY_MS, NULL);
}

/* "Saving Audio" progress dialog.  It owns the SaveReq, kicks off the render
 * (on a worker thread, or inline on the UI thread for SAPI 4), animates a
 * native progress bar, and dismisses itself - returning the success flag -
 * when WM_SA_SAVEDONE arrives. */
#define PROGRESS_TIMER 1
static INT_PTR CALLBACK ProgressDlgProc(HWND dlg, UINT msg, WPARAM wp, LPARAM lp)
{
    SaveReq *req = (SaveReq *)(LONG_PTR)GetWindowLongPtrA(dlg, DWLP_USER);

    switch (msg) {
    case WM_INITDIALOG: {
        const char *p, *fn;
        char lbl[MAX_PATH + 32];
        req = (SaveReq *)lp;
        SetWindowLongPtrA(dlg, DWLP_USER, (LONG_PTR)req);
        req->dlg = dlg;

        /* Label shows the file name only (not the whole path). */
        fn = req->path;
        for (p = req->path; *p; p++) if (*p == '\\' || *p == '/') fn = p + 1;
        wsprintfA(lbl, "Saving audio to %s", fn);
        SetDlgItemTextA(dlg, IDC_PROGRESSLBL, lbl);

        SendDlgItemMessageA(dlg, IDC_PROGRESSBAR, PBM_SETRANGE, 0, MAKELPARAM(0, 100));
        SendDlgItemMessageA(dlg, IDC_PROGRESSBAR, PBM_SETPOS, 0, 0);
        if (g_dark) {       /* match the program's dark theme (classic bar) */
            SendDlgItemMessageA(dlg, IDC_PROGRESSBAR, PBM_SETBKCOLOR, 0, (LPARAM)DARK_CTL);
            SendDlgItemMessageA(dlg, IDC_PROGRESSBAR, PBM_SETBARCOLOR, 0, (LPARAM)RGB(38, 160, 218));
        }
        SetTitleBarDark(dlg, g_dark);
        g_saveStartTick = GetTickCount();
        SetTimer(dlg, PROGRESS_TIMER, 90, NULL);
        SetActiveWindow(dlg);
        SetFocus(GetDlgItem(dlg, IDCANCEL));   /* so NVDA announces the dialog */

        /* SAPI 4 must render on this (UI) thread; everything else renders on a
         * worker so the bar keeps animating.  A failed CreateThread falls back
         * to the inline path too. */
        if (lstrcmpA(req->engine->id, "sapi4") == 0) {
            PostMessageA(dlg, WM_SA_DORENDER, 0, 0);
        } else {
            HANDLE th = CreateThread(NULL, 0, SaveThreadProc, req, 0, NULL);
            if (th) CloseHandle(th);
            else    PostMessageA(dlg, WM_SA_DORENDER, 0, 0);
        }
        return FALSE;   /* focus already set above */
    }

    case WM_SA_DORENDER: {
        /* Inline render.  SAPI 4 pumps the queue itself, so the timer below
         * still fires and the bar animates. */
        BOOL ok = req->engine->SaveToFile(req->engine, req->text, req->asXml,
                                          req->path, req->fmt, req->channels);
        PostMessageA(dlg, WM_SA_SAVEDONE, (WPARAM)ok, (LPARAM)req->fmt);
        return TRUE;
    }

    case WM_TIMER:
        if (wp == PROGRESS_TIMER) {
            /* SAPI exposes no synthesis progress for a file render, so the bar
             * is time-based: it ramps smoothly to 90% over ~10s and then keeps
             * creeping toward 98%, so it never freezes at a cap and read as a
             * hang during a slow voice's render.  WM_SA_SAVEDONE snaps to 100%. */
            DWORD elapsed = GetTickCount() - g_saveStartTick;
            int   pos;
            if (elapsed < 10000) pos = (int)(elapsed * 90 / 10000);
            else { pos = 90 + (int)((elapsed - 10000) / 2000); if (pos > 98) pos = 98; }
            SendDlgItemMessageA(dlg, IDC_PROGRESSBAR, PBM_SETPOS, pos, 0);
        }
        return TRUE;

    case WM_DRAWITEM:
        DrawButton((const DRAWITEMSTRUCT *)lp);   /* owner-draw Cancel button */
        return TRUE;

    case WM_SA_SAVEDONE: {
        BOOL ok        = (BOOL)wp;
        int  fmt       = (int)lp;
        BOOL cancelled = (g_saveCancel != 0);
        char path[MAX_PATH];

        KillTimer(dlg, PROGRESS_TIMER);
        SendDlgItemMessageA(dlg, IDC_PROGRESSBAR, PBM_SETPOS, 100, 0);

        path[0] = 0;
        if (req) {
            lstrcpynA(path, req->path, MAX_PATH);
            Mem_Free(req->text);
            Mem_Free(req);
        }
        SetWindowLongPtrA(dlg, DWLP_USER, 0);
        DestroyWindow(dlg);
        g_progressDlg = NULL;
        g_saving      = FALSE;
        g_saveCancel  = 0;
        SetFocus(g_text);

        if (cancelled) {
            if (path[0]) DeleteFileA(path);   /* discard the partial file */
            SetStatus("Save cancelled");
        } else if (ok) {
            SetStatus("Audio saved");
            /* Defer the toast: posting it lets this handler return and the
             * dialog tear down immediately, instead of stalling on the shell. */
            lstrcpynA(g_savedPath, path, MAX_PATH);
            PostMessageA(g_main, WM_SA_SHOWTOAST, 0, 0);
        } else {
            SetStatus("Save failed");
            MessageBoxA(g_main,
                fmt == FMT_MP3 ?
                "Could not save the MP3 file.\n\nMP3 saving needs an MP3 ACM "
                "encoder or lame.exe (place lame.exe next to Speakalive.exe). "
                "The WAV format always works." :
                "Could not save the audio file.",
                APP_TITLE, MB_OK | MB_ICONERROR);
        }
        return TRUE;
    }

    case WM_CLOSE:
        SendMessageA(dlg, WM_COMMAND, IDCANCEL, 0);   /* X / Alt+F4 = Cancel */
        return TRUE;

    case WM_CTLCOLORDLG:
    case WM_CTLCOLORSTATIC:
    case WM_CTLCOLORBTN:
        if (g_dark) {
            SetTextColor((HDC)wp, DARK_TXT);
            SetBkColor((HDC)wp, DARK_BG);
            return (INT_PTR)g_brBg;
        }
        break;

    case WM_COMMAND:
        if (LOWORD(wp) == IDCANCEL) {
            /* Raise the flag; each engine polls it on its own render thread and
             * stops (SAPI 5 purges, SAPI 4 resets, OneCore cancels the async). */
            if (!g_saveCancel) {
                g_saveCancel = 1;
                SetDlgItemTextA(dlg, IDC_PROGRESSLBL, "Cancelling, please wait...");
                EnableWindow(GetDlgItem(dlg, IDCANCEL), FALSE);
            }
            return TRUE;
        }
        if (LOWORD(wp) == IDOK) return TRUE;   /* ignore Enter */
        break;
    }
    return FALSE;
}

/* Runs off the UI thread so a slow page never freezes the window. */
static DWORD WINAPI WebThread(LPVOID param)
{
    char *url  = (char *)param;
    char *text = Web_FetchText(url);
    Mem_Free(url);
    PostMessageA(g_main, WM_SA_WEBDONE, (WPARAM)text, 0);
    return 0;
}

static void DoWebPage(void)
{
    char  url[2048];
    char *s, *full;
    int   n, i, hasScheme = 0;

    if (g_webBusy) { MessageBeep(MB_ICONASTERISK); return; }
    url[0] = 0;
    if (DialogBoxParamA(g_inst, MAKEINTRESOURCEA(IDD_URL), g_main,
                        UrlDlgProc, (LPARAM)url) != IDOK)
        return;

    s = url;
    while (*s == ' ' || *s == '\t') s++;        /* trim leading spaces */
    if (*s == 0) return;

    n = lstrlenA(s);
    for (i = 0; i + 2 < n; i++)
        if (s[i] == ':' && s[i + 1] == '/' && s[i + 2] == '/') { hasScheme = 1; break; }

    if (hasScheme) {
        full = StrDupA(s);
    } else {
        full = (char *)Mem_Alloc((SIZE_T)n + 8);
        if (full) { lstrcpyA(full, "http://"); lstrcatA(full, s); }
    }
    if (!full) return;

    g_webBusy = TRUE;
    SetStatus("Loading web page...");
    {
        HANDLE th = CreateThread(NULL, 0, WebThread, full, 0, NULL);
        if (th) CloseHandle(th);
        else { Mem_Free(full); g_webBusy = FALSE; SetStatus("Could not start loading"); }
    }
}

static void DoAbout(void)
{
    MessageBoxA(g_main,
        APP_TITLE " version " SA_VERSION "\n"
        "By Seedy.\n"
        "At the speed of light and with the spirit of the community, the Speakonia phoenix flies again.",
        "About " APP_TITLE, MB_OK | MB_ICONINFORMATION);
}

/* ---- layout ---------------------------------------------------------- */

static void MoveCtl(HWND h, int x, int y, int w, int ht)
{
    SetWindowPos(h, NULL, x, y, w, ht, SWP_NOZORDER | SWP_NOACTIVATE);
}

static void Layout(int cw, int ch)
{
    const int M = 8, lblW = 70, valW = 56, rowH = 30, ctlH = 24;
    int statusH = 22, btnH = 26, sliderH;
    int buttonsY, slidersY, textTop, textBottom, sx, sw;
    int stopX, pauseX, speakX;
    RECT rc;

    if (g_status) {
        GetWindowRect(g_status, &rc);
        statusH = rc.bottom - rc.top;
        SendMessageA(g_status, WM_SIZE, 0, 0);
    }

    buttonsY = ch - statusH - M - btnH;
    sliderH  = rowH * 3;
    slidersY = buttonsY - M - sliderH;

    MoveCtl(g_tab,      M, M, cw - 2 * M, 26);
    MoveCtl(g_voiceLbl, M, 42, lblW, ctlH);
    MoveCtl(g_voice,    M + lblW + 6, 40, cw - 2 * M - lblW - 6, 220);
    MoveCtl(g_textLbl,  M, 70, cw - 2 * M, 18);

    textTop = 90;
    textBottom = slidersY - M;
    if (textBottom < textTop + 40) textBottom = textTop + 40;
    MoveCtl(g_text, M, textTop, cw - 2 * M, textBottom - textTop);

    sx = M + lblW + 6;
    sw = cw - 2 * M - lblW - 6 - valW - 6;
    if (sw < 60) sw = 60;
    MoveCtl(g_rateLbl,  M, slidersY + 6,           lblW, ctlH);
    MoveCtl(g_rate,     sx, slidersY,              sw, ctlH);
    MoveCtl(g_rateVal,  sx + sw + 6, slidersY + 6, valW, ctlH);
    MoveCtl(g_pitchLbl, M, slidersY + rowH + 6,    lblW, ctlH);
    MoveCtl(g_pitch,    sx, slidersY + rowH,       sw, ctlH);
    MoveCtl(g_pitchVal, sx + sw + 6, slidersY + rowH + 6, valW, ctlH);
    MoveCtl(g_volLbl,   M, slidersY + 2 * rowH + 6, lblW, ctlH);
    MoveCtl(g_volume,   sx, slidersY + 2 * rowH,   sw, ctlH);
    MoveCtl(g_volVal,   sx + sw + 6, slidersY + 2 * rowH + 6, valW, ctlH);

    MoveCtl(g_reset, M, buttonsY, 130, btnH);
    stopX  = cw - M - 90;
    pauseX = stopX - 6 - 130;
    speakX = pauseX - 6 - 110;
    if (speakX < M + 140) speakX = M + 140;
    MoveCtl(g_speak, speakX, buttonsY, 110, btnH);
    MoveCtl(g_pause, pauseX, buttonsY, 130, btnH);
    MoveCtl(g_stop,  stopX,  buttonsY, 90,  btnH);
}

/* ---- control creation ------------------------------------------------ */

/* The multi-line edit asks for all keys (DLGC_WANTALLKEYS), so IsDialogMessage
 * never gets to navigate away from it.  Subclass it to restore Tab / Shift+Tab
 * navigation and to add Ctrl+A "select all" (which multi-line edits lack). */
static LRESULT CALLBACK EditProc(HWND h, UINT m, WPARAM w, LPARAM l)
{
    switch (m) {
    case WM_KEYDOWN:
        if (w == VK_TAB) {
            BOOL prev = (GetKeyState(VK_SHIFT) & 0x8000) != 0;
            HWND next = GetNextDlgTabItem(g_main, h, prev);
            if (next) SetFocus(next);
            return 0;
        }
        if (w == 'A' && (GetKeyState(VK_CONTROL) & 0x8000)) {
            SendMessageA(h, EM_SETSEL, 0, (LPARAM)-1);
            return 0;
        }
        if (w == VK_ESCAPE) return 0;   /* don't let Escape bubble to a close */
        break;
    case WM_CHAR:
        /* Swallow the characters those keys would otherwise insert.  ESC is
         * important: the default edit proc turns a stray ESC into a WM_CLOSE
         * on the parent window, which would quit the program. */
        if (w == '\t' || w == 1 /* Ctrl+A */ || w == 0x1B /* Esc */) return 0;
        break;
    }
    return CallWindowProcA(g_editOldProc, h, m, w, l);
}

static HWND Child(const char *cls, const char *text, DWORD style, int id)
{
    HWND h = CreateWindowExA(0, cls, text, WS_CHILD | WS_VISIBLE | style,
                             0, 0, 10, 10, g_main, (HMENU)(INT_PTR)id, g_inst, NULL);
    if (h && g_font) SendMessageA(h, WM_SETFONT, (WPARAM)g_font, TRUE);
    return h;
}

static void CreateControls(void)
{
    int i, n;

    g_tab = Child(WC_TABCONTROLA, "", WS_TABSTOP, IDC_TAB);

    g_voiceLbl = Child("STATIC", "&Voice:", SS_LEFT | SS_NOTIFY, IDC_VOICELBL);
    g_voice    = Child("COMBOBOX", "", WS_TABSTOP | WS_VSCROLL |
                       CBS_DROPDOWNLIST | CBS_SORT, IDC_VOICE);

    g_textLbl  = Child("STATIC", "Text to &speak:", SS_LEFT | SS_NOTIFY, IDC_TEXTLBL);
    g_text     = Child("EDIT", "",
                       WS_TABSTOP | WS_BORDER | WS_VSCROLL | ES_MULTILINE |
                       ES_AUTOVSCROLL | ES_WANTRETURN | ES_NOHIDESEL, IDC_TEXT);
    g_editOldProc = (WNDPROC)(LONG_PTR)SetWindowLongPtrA(g_text, GWLP_WNDPROC,
                                                         (LONG_PTR)EditProc);
    /* Allow large content (E.G. a whole web page), not the default ~32 KB. */
    SendMessageA(g_text, EM_SETLIMITTEXT, (WPARAM)0x4000000, 0);

    g_rateLbl  = Child("STATIC", "&Rate:", SS_LEFT | SS_NOTIFY, IDC_RATELBL);
    g_rate     = Child(TRACKBAR_CLASSA, "Rate", WS_TABSTOP | TBS_HORZ |
                       TBS_AUTOTICKS, IDC_RATE);
    g_rateVal  = Child("STATIC", "0", SS_LEFT, IDC_RATEVAL);

    g_pitchLbl = Child("STATIC", "&Pitch:", SS_LEFT | SS_NOTIFY, IDC_PITCHLBL);
    g_pitch    = Child(TRACKBAR_CLASSA, "Pitch", WS_TABSTOP | TBS_HORZ |
                       TBS_AUTOTICKS, IDC_PITCH);
    g_pitchVal = Child("STATIC", "0", SS_LEFT, IDC_PITCHVAL);

    g_volLbl   = Child("STATIC", "Vol&ume:", SS_LEFT | SS_NOTIFY, IDC_VOLLBL);
    g_volume   = Child(TRACKBAR_CLASSA, "Volume", WS_TABSTOP | TBS_HORZ |
                       TBS_AUTOTICKS, IDC_VOLUME);
    g_volVal   = Child("STATIC", "100%", SS_LEFT, IDC_VOLVAL);

    g_reset = Child("BUTTON", "R&eset Sliders", WS_TABSTOP | BS_OWNERDRAW, IDC_RESET);
    g_speak = Child("BUTTON", "Spea&k (F5)", WS_TABSTOP | BS_OWNERDRAW, IDC_SPEAK);
    g_pause = Child("BUTTON", "Pla&y/Pause (F6)", WS_TABSTOP | BS_OWNERDRAW, IDC_PAUSE);
    g_stop  = Child("BUTTON", "S&top (F7)", WS_TABSTOP | BS_OWNERDRAW, IDC_STOP);

    g_status = CreateWindowExA(0, STATUSCLASSNAMEA, "", WS_CHILD | WS_VISIBLE |
                               SBARS_SIZEGRIP, 0, 0, 0, 0, g_main,
                               (HMENU)(INT_PTR)IDC_STATUS, g_inst, NULL);

    /* Slider ranges, ticks and starting positions. */
    SendMessageA(g_rate,   TBM_SETRANGE, TRUE, MAKELONG(RATE_MIN, RATE_MAX));
    SendMessageA(g_rate,   TBM_SETPOS,   TRUE, RATE_DEF);
    SendMessageA(g_rate,   TBM_SETTICFREQ, 5, 0);
    SendMessageA(g_pitch,  TBM_SETRANGE, TRUE, MAKELONG(PITCH_MIN, PITCH_MAX));
    SendMessageA(g_pitch,  TBM_SETPOS,   TRUE, PITCH_DEF);
    SendMessageA(g_pitch,  TBM_SETTICFREQ, 5, 0);
    SendMessageA(g_volume, TBM_SETRANGE, TRUE, MAKELONG(VOL_MIN, VOL_MAX));
    SendMessageA(g_volume, TBM_SETPOS,   TRUE, VOL_DEF);
    SendMessageA(g_volume, TBM_SETTICFREQ, 10, 0);

    /* Populate engine tabs. */
    n = Engines_Count();
    for (i = 0; i < n; i++) {
        TCITEMA ti;
        SpeechEngine *e = Engines_Get(i);
        ZeroMemory(&ti, sizeof(ti));
        ti.mask = TCIF_TEXT;
        ti.pszText = (char *)e->display;
        SendMessageA(g_tab, TCM_INSERTITEMA, i, (LPARAM)&ti);
    }
}

/* ---- window procedure ------------------------------------------------ */

static void HighlightWord(int start, int len)
{
    if (start < 0) start = 0;
    SendMessageA(g_text, EM_SETSEL, (WPARAM)start, (LPARAM)(start + len));
    SendMessageA(g_text, EM_SCROLLCARET, 0, 0);
}

/* ---- dark mode ------------------------------------------------------- */

/* Real OS version, unaffected by the missing app manifest. */
static BOOL IsWin10Plus(void)
{
    typedef LONG (WINAPI *PFN_RtlGetVersion)(void *);
    HMODULE nt = GetModuleHandleA("ntdll.dll");
    if (nt) {
        PFN_RtlGetVersion f = (PFN_RtlGetVersion)GetProcAddress(nt, "RtlGetVersion");
        if (f) {
            OSVERSIONINFOW vi;
            ZeroMemory(&vi, sizeof(vi));
            vi.dwOSVersionInfoSize = sizeof(vi);
            f(&vi);
            return vi.dwMajorVersion >= 10;
        }
    }
    return FALSE;
}

/* The OS "apps use light theme" preference (Win10/11). */
static BOOL ReadOsDark(void)
{
    HKEY  hk;
    DWORD val = 1, sz = sizeof(val);
    BOOL  dark = FALSE;
    if (RegOpenKeyExA(HKEY_CURRENT_USER,
            "Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",
            0, KEY_QUERY_VALUE, &hk) == ERROR_SUCCESS) {
        if (RegQueryValueExA(hk, "AppsUseLightTheme", NULL, NULL,
                             (BYTE *)&val, &sz) == ERROR_SUCCESS)
            dark = (val == 0);
        RegCloseKey(hk);
    }
    return dark;
}

/* Dark title bar on Windows 10 1809+ (ignored elsewhere). */
static void SetTitleBarDark(HWND h, BOOL on)
{
    typedef HRESULT (WINAPI *PFN_Dwm)(HWND, DWORD, LPCVOID, DWORD);
    HMODULE dwm = LoadLibraryA("dwmapi.dll");
    if (dwm) {
        PFN_Dwm f = (PFN_Dwm)GetProcAddress(dwm, "DwmSetWindowAttribute");
        if (f) {
            BOOL v = on;
            if (FAILED(f(h, 20, &v, sizeof(v)))) f(h, 19, &v, sizeof(v));
        }
        FreeLibrary(dwm);
    }
}

static void DrawButton(const DRAWITEMSTRUCT *di)
{
    char txt[128];
    RECT rc = di->rcItem;
    BOOL pressed = (di->itemState & ODS_SELECTED) != 0;
    BOOL focus   = (di->itemState & ODS_FOCUS) != 0;
    BOOL disabled= (di->itemState & ODS_DISABLED) != 0;

    GetWindowTextA(di->hwndItem, txt, sizeof(txt));
    SetBkMode(di->hDC, TRANSPARENT);

    if (g_dark) {
        HBRUSH fill = CreateSolidBrush(pressed ? DARK_CTL : DARK_BTN);
        HPEN   pen  = CreatePen(PS_SOLID, 1, DARK_EDGE);
        HGDIOBJ op  = SelectObject(di->hDC, pen);
        HGDIOBJ ob  = SelectObject(di->hDC, fill);
        Rectangle(di->hDC, rc.left, rc.top, rc.right, rc.bottom);
        SelectObject(di->hDC, op);
        SelectObject(di->hDC, ob);
        DeleteObject(pen);
        DeleteObject(fill);
        SetTextColor(di->hDC, disabled ? DARK_DIS : DARK_TXT);
    } else {
        UINT s = DFCS_BUTTONPUSH | (pressed ? DFCS_PUSHED : 0) |
                 (disabled ? DFCS_INACTIVE : 0);
        DrawFrameControl(di->hDC, &rc, DFC_BUTTON, s);
        SetTextColor(di->hDC, GetSysColor(disabled ? COLOR_GRAYTEXT : COLOR_BTNTEXT));
    }
    if (pressed) OffsetRect(&rc, 1, 1);
    DrawTextA(di->hDC, txt, -1, &rc, DT_CENTER | DT_VCENTER | DT_SINGLELINE);
    if (focus) {
        RECT fr = di->rcItem;
        InflateRect(&fr, -3, -3);
        DrawFocusRect(di->hDC, &fr);
    }
}

static void DrawStatusPart(const DRAWITEMSTRUCT *di)
{
    RECT   rc = di->rcItem;
    HBRUSH b  = CreateSolidBrush(DARK_BG);
    FillRect(di->hDC, &rc, b);
    DeleteObject(b);
    SetBkMode(di->hDC, TRANSPARENT);
    SetTextColor(di->hDC, DARK_TXT);
    rc.left += 2;
    if (di->itemData)
        DrawTextA(di->hDC, (const char *)di->itemData, -1, &rc,
                  DT_LEFT | DT_VCENTER | DT_SINGLELINE);
}

static void ApplyDark(BOOL on)
{
    g_dark = on;
    if (g_brBg)  { DeleteObject(g_brBg);  g_brBg = NULL; }
    if (g_brCtl) { DeleteObject(g_brCtl); g_brCtl = NULL; }
    if (on) {
        g_brBg  = CreateSolidBrush(DARK_BG);
        g_brCtl = CreateSolidBrush(DARK_CTL);
    }
    if (g_status)
        SendMessageA(g_status, SB_SETBKCOLOR, 0, (LPARAM)(on ? DARK_BG : CLR_DEFAULT));
    SetStatus(g_statusText);   /* re-send with/without owner-draw flag */
    if (g_menu)
        CheckMenuItem(g_menu, IDM_DARKMODE, MF_BYCOMMAND | (on ? MF_CHECKED : MF_UNCHECKED));
    if (g_main) {
        SetTitleBarDark(g_main, on);
        InvalidateRect(g_main, NULL, TRUE);
        RedrawWindow(g_main, NULL, NULL,
                     RDW_INVALIDATE | RDW_ERASE | RDW_ALLCHILDREN);
        /* Trackbars cache their channel background and don't repaint it on a
         * plain invalidate.  When the window is already visible (a live theme
         * toggle), nudge the size by a pixel so WM_SIZE forces a full relayout
         * and the channels repaint in the new colours. */
        if (IsWindowVisible(g_main)) {
            RECT wr;
            int  w, h;
            GetWindowRect(g_main, &wr);
            w = wr.right - wr.left;
            h = wr.bottom - wr.top;
            /* Width drives the slider width, so changing it forces the
             * trackbars to resize and repaint their cached channels. */
            SetWindowPos(g_main, NULL, 0, 0, w - 1, h,
                         SWP_NOMOVE | SWP_NOZORDER | SWP_NOACTIVATE);
            SetWindowPos(g_main, NULL, 0, 0, w, h,
                         SWP_NOMOVE | SWP_NOZORDER | SWP_NOACTIVATE);
        }
    }
}

/* ---- settings persistence (registry) --------------------------------- */

#define SA_REGKEY "Software\\Speakalive"

static void RegSetDword(HKEY k, const char *name, DWORD v)
{
    RegSetValueExA(k, name, 0, REG_DWORD, (const BYTE *)&v, sizeof(v));
}
static DWORD RegGetDword(HKEY k, const char *name, DWORD def)
{
    DWORD v = def, sz = sizeof(v), type = 0;
    if (RegQueryValueExA(k, name, NULL, &type, (BYTE *)&v, &sz) == ERROR_SUCCESS &&
        type == REG_DWORD)
        return v;
    return def;
}
static void RegSetStr(HKEY k, const char *name, const char *s)
{
    RegSetValueExA(k, name, 0, REG_SZ, (const BYTE *)s, (DWORD)lstrlenA(s) + 1);
}
static void RegGetStr(HKEY k, const char *name, char *buf, DWORD len)
{
    DWORD sz = len, type = 0;
    buf[0] = 0;
    if (RegQueryValueExA(k, name, NULL, &type, (BYTE *)buf, &sz) != ERROR_SUCCESS ||
        type != REG_SZ)
        buf[0] = 0;
    buf[len - 1] = 0;
}
static int ClampI(int v, int lo, int hi) { return v < lo ? lo : (v > hi ? hi : v); }

/* ---- audio output device -------------------------------------------------
 * Every engine reads Audio_DeviceId() when it opens its output.  The choice is
 * remembered by NAME (a waveOut index can shift as devices come and go) and
 * resolved to a live index on demand; a blank name means the system default. */
static HMENU g_audioMenu = NULL;      /* the "Audio Output Device" submenu */
static char  g_audioDevName[40];      /* chosen device name, "" = default  */

/* Match the remembered name against the devices present now and publish the
 * resulting index (or default) for the engines. */
static void AudioDeviceResolve(void)
{
    UINT n, i;
    Audio_SetDeviceId(AUDIO_DEV_DEFAULT);
    if (g_audioDevName[0] == 0) return;
    n = waveOutGetNumDevs();
    for (i = 0; i < n; i++) {
        WAVEOUTCAPSA caps;
        if (waveOutGetDevCapsA(i, &caps, sizeof(caps)) == MMSYSERR_NOERROR &&
            lstrcmpiA(g_audioDevName, caps.szPname) == 0) {
            Audio_SetDeviceId(i);
            return;
        }
    }
    /* Not present just now: stay on the default until it comes back. */
}

/* Rebuild the submenu from the devices present now, ticking the current one. */
static void AudioMenuBuild(void)
{
    UINT n, i, cur;
    if (!g_audioMenu) return;
    AudioDeviceResolve();
    cur = Audio_DeviceId();
    while (GetMenuItemCount(g_audioMenu) > 0) DeleteMenu(g_audioMenu, 0, MF_BYPOSITION);
    AppendMenuA(g_audioMenu, MF_STRING | (cur == AUDIO_DEV_DEFAULT ? MF_CHECKED : 0),
                IDM_AUDIODEV_BASE, "&Default (system's choice)");
    n = waveOutGetNumDevs();
    for (i = 0; i < n && i < IDM_AUDIODEV_MAX - 1; i++) {
        WAVEOUTCAPSA caps;
        if (waveOutGetDevCapsA(i, &caps, sizeof(caps)) == MMSYSERR_NOERROR)
            AppendMenuA(g_audioMenu, MF_STRING | (cur == i ? MF_CHECKED : 0),
                        IDM_AUDIODEV_BASE + 1 + i, caps.szPname);
    }
}

/* Push a just-picked device to the running engine.  SAPI 5 rebinds on its next
 * Speak and OneCore reopens on its next play, so they need nothing here; SAPI 4
 * binds its device when a voice is selected, so re-select to move it now. */
static void AudioApplyToEngine(void)
{
    if (!g_engine || g_speaking || g_saving) return;
    if (lstrcmpA(g_engine->id, "sapi4") == 0 && g_engine->SetVoice) {
        int sel = (int)SendMessageA(g_voice, CB_GETCURSEL, 0, 0);
        if (sel >= 0) {
            int idx = (int)SendMessageA(g_voice, CB_GETITEMDATA, sel, 0);
            if (idx >= 0) g_engine->SetVoice(g_engine, idx);
        }
    }
}

/* Handle a device menu choice: remember it (blank = default), persist, apply. */
static void AudioDevicePick(int cmd)
{
    HKEY k;
    int  slot = cmd - IDM_AUDIODEV_BASE;   /* 0 = default, else device slot-1 */
    if (slot <= 0) {
        g_audioDevName[0] = 0;
    } else {
        WAVEOUTCAPSA caps;
        if (waveOutGetDevCapsA((UINT)(slot - 1), &caps, sizeof(caps)) != MMSYSERR_NOERROR)
            return;
        lstrcpynA(g_audioDevName, caps.szPname, sizeof(g_audioDevName));
    }
    AudioDeviceResolve();
    if (RegCreateKeyExA(HKEY_CURRENT_USER, SA_REGKEY, 0, NULL, 0, KEY_SET_VALUE,
                        NULL, &k, NULL) == ERROR_SUCCESS) {
        RegSetStr(k, "AudioDevice", g_audioDevName);
        RegCloseKey(k);
    }
    AudioApplyToEngine();
    if (g_audioDevName[0]) {
        char msg[80];
        wsprintfA(msg, "Audio output: %s", g_audioDevName);
        SetStatus(msg);
    } else {
        SetStatus("Audio output: default device");
    }
}

/* Create the (empty) submenu and hang it in the Speech menu; resolve the saved
 * choice.  Called once at start-up after the menu is loaded. */
static void AudioMenuInit(void)
{
    HMENU speech = GetSubMenu(g_menu, 1);   /* File = 0, Speech = 1 */
    g_audioMenu = CreatePopupMenu();
    if (speech && g_audioMenu)
        InsertMenuA(speech, IDM_HIGHLIGHT, MF_BYCOMMAND | MF_POPUP | MF_STRING,
                    (UINT_PTR)g_audioMenu, "Audio Output &Device");
    AudioDeviceResolve();
}

static void LoadSettings(void)
{
    HKEY k;
    g_loadRate = RATE_DEF; g_loadPitch = PITCH_DEF; g_loadVol = VOL_DEF;
    g_loadDark = 0; g_loadFollowOs = 1;
    g_loadEngine[0] = 0; g_loadVoice[0] = 0;

    if (RegOpenKeyExA(HKEY_CURRENT_USER, SA_REGKEY, 0, KEY_QUERY_VALUE, &k) != ERROR_SUCCESS)
        return;
    g_haveSettings = 1;
    g_xmlMode   = RegGetDword(k, "XmlMode",   (DWORD)g_xmlMode)   ? TRUE : FALSE;
    g_highlight = RegGetDword(k, "Highlight", (DWORD)g_highlight) ? TRUE : FALSE;
    g_stereo    = RegGetDword(k, "Stereo",    (DWORD)g_stereo)    ? TRUE : FALSE;
    g_loadDark     = RegGetDword(k, "Dark", 0)     ? 1 : 0;
    g_loadFollowOs = RegGetDword(k, "FollowOs", 1) ? 1 : 0;
    g_loadRate  = ClampI((int)RegGetDword(k, "Rate",   RATE_DEF),  RATE_MIN,  RATE_MAX);
    g_loadPitch = ClampI((int)RegGetDword(k, "Pitch",  PITCH_DEF), PITCH_MIN, PITCH_MAX);
    g_loadVol   = ClampI((int)RegGetDword(k, "Volume", VOL_DEF),   VOL_MIN,   VOL_MAX);
    RegGetStr(k, "Engine", g_loadEngine, sizeof(g_loadEngine));
    RegGetStr(k, "Voice",  g_loadVoice,  sizeof(g_loadVoice));
    RegGetStr(k, "AudioDevice", g_audioDevName, sizeof(g_audioDevName));
    RegCloseKey(k);
}

static void SaveSettings(void)
{
    HKEY k;
    WINDOWPLACEMENT wp;
    int sel;
    if (RegCreateKeyExA(HKEY_CURRENT_USER, SA_REGKEY, 0, NULL, 0, KEY_SET_VALUE,
                        NULL, &k, NULL) != ERROR_SUCCESS)
        return;
    RegSetDword(k, "XmlMode",   (DWORD)(g_xmlMode   ? 1 : 0));
    RegSetDword(k, "Highlight", (DWORD)(g_highlight ? 1 : 0));
    RegSetDword(k, "Stereo",    (DWORD)(g_stereo    ? 1 : 0));
    RegSetDword(k, "Dark",      (DWORD)(g_dark      ? 1 : 0));
    RegSetDword(k, "FollowOs",  (DWORD)(g_followOs  ? 1 : 0));
    RegSetDword(k, "Rate",   (DWORD)TbPos(g_rate));
    RegSetDword(k, "Pitch",  (DWORD)TbPos(g_pitch));
    RegSetDword(k, "Volume", (DWORD)TbPos(g_volume));
    if (g_engine && g_engine->id) RegSetStr(k, "Engine", g_engine->id);
    sel = (int)SendMessageA(g_voice, CB_GETCURSEL, 0, 0);
    if (sel >= 0) {
        int tl = (int)SendMessageA(g_voice, CB_GETLBTEXTLEN, sel, 0);
        if (tl > 0 && tl < 256) {
            char vn[256];
            SendMessageA(g_voice, CB_GETLBTEXT, sel, (LPARAM)vn);
            RegSetStr(k, "Voice", vn);
        }
    }
    ZeroMemory(&wp, sizeof(wp));
    wp.length = sizeof(wp);
    if (GetWindowPlacement(g_main, &wp))
        RegSetValueExA(k, "WindowPlacement", 0, REG_BINARY, (const BYTE *)&wp, sizeof(wp));
    RegCloseKey(k);
}

static void SelectVoiceByName(const char *name)
{
    int n = (int)SendMessageA(g_voice, CB_GETCOUNT, 0, 0), i;
    if (!name[0]) return;
    for (i = 0; i < n; i++) {
        int tl = (int)SendMessageA(g_voice, CB_GETLBTEXTLEN, i, 0);
        if (tl > 0 && tl < 256) {
            char vn[256];
            SendMessageA(g_voice, CB_GETLBTEXT, i, (LPARAM)vn);
            if (lstrcmpA(vn, name) == 0) {
                SendMessageA(g_voice, CB_SETCURSEL, i, 0);
                if (g_engine && g_engine->SetVoice)
                    g_engine->SetVoice(g_engine,
                        (int)SendMessageA(g_voice, CB_GETITEMDATA, i, 0));
                return;
            }
        }
    }
}

static int RestoreWindowPlacement(HWND h)
{
    HKEY k;
    WINDOWPLACEMENT wp;
    DWORD sz = sizeof(wp), type = 0;
    int ok = 0;
    ZeroMemory(&wp, sizeof(wp));
    if (RegOpenKeyExA(HKEY_CURRENT_USER, SA_REGKEY, 0, KEY_QUERY_VALUE, &k) != ERROR_SUCCESS)
        return 0;
    if (RegQueryValueExA(k, "WindowPlacement", NULL, &type, (BYTE *)&wp, &sz) == ERROR_SUCCESS &&
        type == REG_BINARY && sz == sizeof(wp) && wp.length == sizeof(wp)) {
        if (wp.showCmd == SW_SHOWMINIMIZED || wp.showCmd == SW_MINIMIZE)
            wp.showCmd = SW_SHOWNORMAL;        /* never start minimised */
        SetWindowPlacement(h, &wp);
        ok = 1;
    }
    RegCloseKey(k);
    return ok;
}

/* ---- autosave / crash recovery --------------------------------------- */

/* Build %APPDATA%\Speakalive\recover.txt (creating the folder). */
static BOOL GetRecoverPath(char *buf, int len)
{
    char base[MAX_PATH];
    DWORD n = GetEnvironmentVariableA("APPDATA", base, MAX_PATH);
    if (n == 0 || n >= MAX_PATH) return FALSE;
    if (lstrlenA(base) + 24 >= len) return FALSE;
    lstrcpynA(buf, base, len);
    lstrcatA(buf, "\\Speakalive");
    CreateDirectoryA(buf, NULL);                 /* ignore "already exists" */
    lstrcatA(buf, "\\recover.txt");
    return TRUE;
}

/* Write the current text to the recovery file (or remove it when empty). */
static void AutoSave(void)
{
    char  path[MAX_PATH];
    char *text;
    int   n;
    if (!GetRecoverPath(path, sizeof(path))) return;
    text = GetEditText();
    n = text ? lstrlenA(text) : 0;
    if (n == 0) {
        DeleteFileA(path);
    } else {
        HANDLE h = CreateFileA(path, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS,
                               FILE_ATTRIBUTE_NORMAL, NULL);
        if (h != INVALID_HANDLE_VALUE) {
            DWORD w;
            WriteFile(h, text, (DWORD)n, &w, NULL);
            CloseHandle(h);
        }
    }
    Mem_Free(text);
    g_dirty = FALSE;
}

/* On start-up, if a recovery file exists it means the last session did not
 * close cleanly (crash / power loss), so offer to restore the text. */
static void CheckRecovery(void)
{
    char   path[MAX_PATH];
    HANDLE h;
    DWORD  size, got;
    char  *buf;

    if (!GetRecoverPath(path, sizeof(path))) return;
    h = CreateFileA(path, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING,
                    FILE_ATTRIBUTE_NORMAL, NULL);
    if (h == INVALID_HANDLE_VALUE) return;          /* clean last exit */
    size = GetFileSize(h, NULL);
    if (size == 0 || size == INVALID_FILE_SIZE) { CloseHandle(h); DeleteFileA(path); return; }

    if (MessageBoxA(g_main,
            "Speakalive did not close properly last time.\n\n"
            "Recover the text you were working on?",
            APP_TITLE, MB_YESNO | MB_ICONQUESTION) == IDYES) {
        buf = (char *)Mem_Alloc((SIZE_T)size + 1);
        if (buf) {
            if (ReadFile(h, buf, size, &got, NULL)) {
                buf[got] = 0;
                SetWindowTextA(g_text, buf);
                /* Recovered text is unsaved work - mark it so, so exiting
                 * prompts to save and autosave keeps protecting it. */
                g_modified = TRUE;
                g_dirty    = TRUE;
                SetStatus("Recovered text from the last session");
            }
            Mem_Free(buf);
        }
    } else {
        DeleteFileA(path);                          /* user declined - discard */
    }
    CloseHandle(h);
}

/* Returns TRUE if it is OK to exit.  Prompts to save the text (not audio - you
 * cannot recover text from a .wav) when there are unsaved changes. */
static BOOL ConfirmExit(void)
{
    char *text;
    int   n, ans;
    if (!g_modified) return TRUE;          /* nothing unsaved */
    text = GetEditText();
    n = text ? lstrlenA(text) : 0;
    Mem_Free(text);
    if (n == 0) return TRUE;               /* empty - nothing to save */

    ans = MessageBoxA(g_main,
            "You have unsaved text.\n\nSave it before exiting?",
            APP_TITLE, MB_YESNOCANCEL | MB_ICONWARNING);
    if (ans == IDCANCEL) return FALSE;     /* stay open */
    if (ans == IDYES) {
        DoSaveText();                      /* shows the Save Text dialog */
        if (g_modified) return FALSE;      /* save was cancelled - don't exit */
    }
    return TRUE;                           /* No, or saved successfully */
}

static LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    switch (msg) {
    case WM_CREATE: {
        int i, def = 0, count;
        LOGFONTA lf;
        g_main = hwnd;
        if (SystemParametersInfoA(SPI_GETICONTITLELOGFONT, sizeof(lf), &lf, 0))
            g_font = CreateFontIndirectA(&lf);
        if (!g_font) g_font = (HFONT)GetStockObject(DEFAULT_GUI_FONT);

        CreateControls();
        LoadSettings();

        /* Restore the saved slider positions before SwitchEngine applies them. */
        SendMessageA(g_rate,   TBM_SETPOS, TRUE, g_loadRate);
        SendMessageA(g_pitch,  TBM_SETPOS, TRUE, g_loadPitch);
        SendMessageA(g_volume, TBM_SETPOS, TRUE, g_loadVol);

        count = Engines_Count();
        if (count == 0) {
            SetStatus("No speech engines found on this system");
            EnableWindow(g_speak, FALSE);
            EnableWindow(g_pause, FALSE);
            EnableWindow(g_stop, FALSE);
        } else {
            /* Prefer the saved engine, then SAPI 5, then the first present. */
            def = -1;
            if (g_loadEngine[0])
                for (i = 0; i < count; i++) {
                    SpeechEngine *e = Engines_Get(i);
                    if (e && e->id && lstrcmpA(e->id, g_loadEngine) == 0) { def = i; break; }
                }
            if (def < 0)
                for (i = 0; i < count; i++) {
                    SpeechEngine *e = Engines_Get(i);
                    if (e && e->id && lstrcmpA(e->id, "sapi5") == 0) { def = i; break; }
                }
            if (def < 0) def = 0;
            SendMessageA(g_tab, TCM_SETCURSEL, def, 0);
            SwitchEngine(def);
            SelectVoiceByName(g_loadVoice);
        }

        CheckMenuItem(g_menu, IDM_XML,
                      MF_BYCOMMAND | (g_xmlMode ? MF_CHECKED : MF_UNCHECKED));
        CheckMenuItem(g_menu, IDM_HIGHLIGHT,
                      MF_BYCOMMAND | (g_highlight ? MF_CHECKED : MF_UNCHECKED));
        Sapi5_SetWordHighlight(g_highlight);   /* request word events only if on */
        CheckMenuItem(g_menu, IDM_STEREO,
                      MF_BYCOMMAND | (g_stereo ? MF_CHECKED : MF_UNCHECKED));

        /* Dark mode: on Win10/11 follow the OS setting by default (or the saved
         * choice); on older Windows "Follow OS" is unavailable and the saved
         * manual state is restored. */
        if (IsWin10Plus()) {
            g_followOs = g_haveSettings ? (g_loadFollowOs ? TRUE : FALSE) : TRUE;
            CheckMenuItem(g_menu, IDM_FOLLOWOS,
                          MF_BYCOMMAND | (g_followOs ? MF_CHECKED : MF_UNCHECKED));
        } else {
            g_followOs = FALSE;
            EnableMenuItem(g_menu, IDM_FOLLOWOS, MF_BYCOMMAND | MF_GRAYED);
        }
        ApplyDark(g_followOs ? ReadOsDark()
                             : (g_haveSettings && g_loadDark ? TRUE : FALSE));

        SetTimer(hwnd, TIMER_AUTOSAVE, AUTOSAVE_MS, NULL);
        SetFocus(g_text);
        return 0;
    }

    case WM_TIMER:
        if (wp == TIMER_AUTOSAVE && g_dirty) AutoSave();
        if (wp == TIMER_TRAY) RemoveTrayIcon();   /* balloon backstop timeout */
        return 0;

    case WM_SA_SHOWTOAST:
        ShowSaveNotification(g_savedPath);  /* off the save-completion path */
        return 0;

    case WM_SA_TRAY:
        /* The save toast/balloon was dismissed or timed out - drop the icon. */
        if (LOWORD(lp) == NIN_BALLOONTIMEOUT ||
            LOWORD(lp) == NIN_BALLOONHIDE ||
            LOWORD(lp) == NIN_BALLOONUSERCLICK)
            RemoveTrayIcon();
        return 0;

    case WM_SIZE:
        Layout(LOWORD(lp), HIWORD(lp));
        return 0;

    case WM_ACTIVATE:
        /* Remember which control had focus when we lose activation, and put it
         * back when we return (E.G. after Alt+Tab), instead of letting focus
         * default to an arbitrary control. */
        if (LOWORD(wp) == WA_INACTIVE) {
            HWND f = GetFocus();
            if (f && IsChild(hwnd, f)) g_lastFocus = f;
        } else if (g_lastFocus && IsWindow(g_lastFocus)) {
            SetFocus(g_lastFocus);
        }
        return 0;

    case WM_GETMINMAXINFO: {
        MINMAXINFO *mmi = (MINMAXINFO *)lp;
        mmi->ptMinTrackSize.x = 520;
        mmi->ptMinTrackSize.y = 440;
        return 0;
    }

    case WM_ERASEBKGND:
        if (g_dark && g_brBg) {
            RECT rc;
            GetClientRect(hwnd, &rc);
            FillRect((HDC)wp, &rc, g_brBg);
            return 1;
        }
        break;

    case WM_CTLCOLOREDIT:
    case WM_CTLCOLORLISTBOX:
        if (g_dark) {
            SetTextColor((HDC)wp, DARK_TXT);
            SetBkColor((HDC)wp, DARK_CTL);
            return (LRESULT)g_brCtl;
        }
        break;

    case WM_CTLCOLORSTATIC:
    case WM_CTLCOLORBTN:
        if (g_dark) {
            SetTextColor((HDC)wp, DARK_TXT);
            SetBkColor((HDC)wp, DARK_BG);
            return (LRESULT)g_brBg;
        }
        break;

    case WM_DRAWITEM: {
        DRAWITEMSTRUCT *di = (DRAWITEMSTRUCT *)lp;
        if (di->CtlType == ODT_BUTTON) { DrawButton(di); return TRUE; }
        if (di->hwndItem == g_status)  { DrawStatusPart(di); return TRUE; }
        break;
    }

    case WM_SETTINGCHANGE:
        /* Follow the OS light/dark preference when the user opted in. */
        if (g_followOs && lp &&
            lstrcmpiA((const char *)lp, "ImmersiveColorSet") == 0)
            ApplyDark(ReadOsDark());
        return 0;

    case WM_HSCROLL:
        if (!g_saving &&
            ((HWND)lp == g_rate || (HWND)lp == g_pitch || (HWND)lp == g_volume)) {
            ApplyAllSliders();
        }
        return 0;

    case WM_NOTIFY: {
        LPNMHDR nh = (LPNMHDR)lp;
        if (nh->hwndFrom == g_tab && nh->code == TCN_SELCHANGE) {
            int sel = (int)SendMessageA(g_tab, TCM_GETCURSEL, 0, 0);
            if (g_saving) {
                /* Can't switch engines mid-render - put the tab back. */
                SendMessageA(g_tab, TCM_SETCURSEL, g_engineIndex, 0);
                SetStatus("Please wait - saving audio");
            } else {
                SwitchEngine(sel);
            }
            /* Keep focus on the tab control so the user can keep arrowing
             * through the engine tabs. */
        }
        return 0;
    }

    case WM_COMMAND: {
        int id = LOWORD(wp);
        int code = HIWORD(wp);
        if ((HWND)lp == g_voice && code == CBN_SELCHANGE) {
            int sel = (int)SendMessageA(g_voice, CB_GETCURSEL, 0, 0);
            if (!g_saving && sel >= 0 && g_engine && g_engine->SetVoice)
                g_engine->SetVoice(g_engine,
                    (int)SendMessageA(g_voice, CB_GETITEMDATA, sel, 0));
            return 0;
        }
        if ((HWND)lp == g_text && code == EN_CHANGE) {
            g_dirty = TRUE;      /* mark for the next autosave tick    */
            g_modified = TRUE;   /* unsaved text (for the exit prompt) */
            return 0;
        }
        if (id >= IDM_AUDIODEV_BASE && id < IDM_AUDIODEV_BASE + IDM_AUDIODEV_MAX) {
            AudioDevicePick(id);
            return 0;
        }
        switch (id) {
        case IDC_SPEAK: case IDM_SPEAK: DoSpeak();     return 0;
        case IDC_PAUSE: case IDM_PAUSE: DoPlayPause();  return 0;
        case IDC_STOP:  case IDM_STOP:  DoStop();       return 0;
        case IDM_NEXTENGINE: CycleEngine(+1);          return 0;
        case IDM_PREVENGINE: CycleEngine(-1);          return 0;
        case IDC_RESET: case IDM_RESET: DoReset();      return 0;
        case IDM_SAVE:                  DoSave();       return 0;
        case IDM_SAVETEXT:              DoSaveText();   return 0;
        case IDM_WEBPAGE:               DoWebPage();    return 0;
        case IDM_RENAMEVOICE:           DoRenameVoice(); return 0;
        case IDM_VOICEEXPORT:           DoBackupVoiceNames();  return 0;
        case IDM_VOICEIMPORT:           DoRestoreVoiceNames(); return 0;
        case IDM_TAGS:                  DoShowTags();   return 0;
        case IDM_ABOUT:                 DoAbout();      return 0;
        case IDM_EXIT:  SendMessageA(hwnd, WM_CLOSE, 0, 0); return 0;
        case IDM_XML:
            g_xmlMode = !g_xmlMode;
            CheckMenuItem(g_menu, IDM_XML,
                MF_BYCOMMAND | (g_xmlMode ? MF_CHECKED : MF_UNCHECKED));
            SetStatus(g_xmlMode ? "XML / SSML markup enabled"
                                : "XML / SSML markup disabled");
            return 0;
        case IDM_HIGHLIGHT:
            g_highlight = !g_highlight;
            CheckMenuItem(g_menu, IDM_HIGHLIGHT,
                MF_BYCOMMAND | (g_highlight ? MF_CHECKED : MF_UNCHECKED));
            Sapi5_SetWordHighlight(g_highlight); /* (de)register word events */
            SetStatus(g_highlight ? "Spoken word highlighting on"
                                  : "Spoken word highlighting off");
            return 0;
        case IDM_STEREO:
            g_stereo = !g_stereo;
            CheckMenuItem(g_menu, IDM_STEREO,
                MF_BYCOMMAND | (g_stereo ? MF_CHECKED : MF_UNCHECKED));
            SetStatus(g_stereo ? "Audio will be saved in stereo"
                               : "Audio will be saved in mono");
            return 0;
        case IDM_DARKMODE:
            /* A manual choice overrides automatic following. */
            g_followOs = FALSE;
            CheckMenuItem(g_menu, IDM_FOLLOWOS, MF_BYCOMMAND | MF_UNCHECKED);
            ApplyDark(!g_dark);
            SetStatus(g_dark ? "Dark mode on" : "Dark mode off");
            return 0;
        case IDM_FOLLOWOS:
            g_followOs = !g_followOs;
            CheckMenuItem(g_menu, IDM_FOLLOWOS,
                          MF_BYCOMMAND | (g_followOs ? MF_CHECKED : MF_UNCHECKED));
            if (g_followOs) {
                ApplyDark(ReadOsDark());
                SetStatus("Following OS dark mode");
            } else {
                SetStatus("No longer following OS dark mode");
            }
            return 0;
        }
        return 0;
    }

    case WM_SA_SAPI5EVENT:
        /* While a background save is rendering on the worker thread, draining
         * events here would call GetEvents on the very voice the worker is
         * mid-Speak on, blocking the UI thread for the whole render.  Skip it;
         * the queued events are harmless and cleared on the next speak. */
        if (!g_saving) Sapi5_PumpEvents();
        return 0;
    case WM_SA_OCPLAY:
        OneCore_DoPlay((char *)wp, (long)lp);
        return 0;
    case WM_SA_S4NEXT:               /* SAPI 4 finished a chunk - feed the next */
        Sapi4_SpeakNextChunk((long)wp);
        return 0;

    case WM_INITMENUPOPUP:
        /* Fill the Audio Output Device submenu with the devices present now. */
        if ((HMENU)wp == g_audioMenu) AudioMenuBuild();
        break;   /* let DefWindowProc do the standard menu init too */
    case WM_DEVICECHANGE:
        AudioDeviceResolve();   /* an output device may have come or gone */
        break;

    case WM_SA_WORD:
        if (g_highlight) HighlightWord((int)wp, (int)lp);
        return 0;
    case WM_SA_STARTED:
        g_speaking = TRUE; g_paused = FALSE;
        SetStatus("Speaking");
        return 0;
    case WM_SA_DONE:
        g_speaking = FALSE; g_paused = FALSE;
        SetStatus("Ready");
        return 0;

    case WM_SA_WEBDONE: {
        char *text = (char *)wp;
        g_webBusy = FALSE;
        if (text) {
            SetWindowTextA(g_text, text);
            Mem_Free(text);
            /* SetWindowText does not raise EN_CHANGE, so flag the unsaved
             * state ourselves - otherwise the exit prompt and autosave would
             * not realise the loaded page is unsaved work. */
            g_modified = TRUE;
            g_dirty    = TRUE;
            SetStatus("Web page loaded - press F5 to speak");
            SetFocus(g_text);
        } else {
            SetStatus("Could not load the web page");
            MessageBoxA(g_main,
                "Could not load that web page.\n\n"
                "Check the address and your internet connection.",
                APP_TITLE, MB_OK | MB_ICONERROR);
        }
        return 0;
    }

    case WM_CLOSE:
        if (g_saving) {                 /* a background render is still running */
            SetStatus("Please wait - finish saving audio before exiting");
            MessageBeep(MB_ICONWARNING);
            return 0;
        }
        if (!ConfirmExit()) return 0;   /* user chose Cancel */
        DestroyWindow(hwnd);
        return 0;

    case WM_DESTROY: {
        char path[MAX_PATH];
        KillTimer(hwnd, TIMER_AUTOSAVE);
        RemoveTrayIcon();
        SaveSettings();
        /* A clean exit means there is nothing to recover next time. */
        if (GetRecoverPath(path, sizeof(path))) DeleteFileA(path);
        Engines_ShutdownAll();
        if (g_font)  DeleteObject(g_font);
        if (g_brBg)  DeleteObject(g_brBg);
        if (g_brCtl) DeleteObject(g_brCtl);
        PostQuitMessage(0);
        return 0;
    }
    }
    return DefWindowProcA(hwnd, msg, wp, lp);
}

/* ---- entry ----------------------------------------------------------- */

int SpeakaliveMain(void)
{
    WNDCLASSEXA wc;
    INITCOMMONCONTROLSEX icc;
    HACCEL accel;
    MSG msg;
    HANDLE single;

    g_inst = GetModuleHandleA(NULL);

    /* Single instance: if another Speakalive is already running in this session,
     * bring its window to the front and quietly exit.  The mutex handle is held
     * open for our whole run (released automatically when we exit) so later
     * launches keep seeing ERROR_ALREADY_EXISTS. */
    single = CreateMutexA(NULL, FALSE, "SpeakaliveSingleInstance.cdfn");
    if (single && GetLastError() == ERROR_ALREADY_EXISTS) {
        HWND prev = FindWindowA(APP_CLASS, NULL);
        if (prev) {
            if (IsIconic(prev)) ShowWindow(prev, SW_RESTORE);
            SetForegroundWindow(prev);
        }
        CloseHandle(single);
        return 0;
    }

    CoInitializeEx(NULL, COINIT_APARTMENTTHREADED);

    icc.dwSize = sizeof(icc);
    icc.dwICC  = ICC_BAR_CLASSES | ICC_TAB_CLASSES | ICC_PROGRESS_CLASS |
                 ICC_LISTVIEW_CLASSES;
    InitCommonControlsEx(&icc);

    Engines_Init();

    ZeroMemory(&wc, sizeof(wc));
    wc.cbSize        = sizeof(wc);
    wc.lpfnWndProc   = WndProc;
    wc.hInstance     = g_inst;
    wc.hIcon         = LoadIconA(NULL, (LPCSTR)IDI_APPLICATION);
    wc.hCursor       = LoadCursorA(NULL, (LPCSTR)IDC_ARROW);
    wc.hbrBackground = (HBRUSH)(COLOR_BTNFACE + 1);
    wc.lpszClassName = APP_CLASS;
    wc.hIconSm       = wc.hIcon;
    RegisterClassExA(&wc);

    g_menu = LoadMenuA(g_inst, MAKEINTRESOURCEA(IDR_MENU));
    AudioMenuInit();   /* add the Audio Output Device submenu, resolve the saved choice */

    g_main = CreateWindowExA(0, APP_CLASS, APP_TITLE,
                             WS_OVERLAPPEDWINDOW | WS_CLIPCHILDREN,
                             CW_USEDEFAULT, CW_USEDEFAULT, 660, 540,
                             NULL, g_menu, g_inst, NULL);
    if (!g_main) return 1;

    /* Restore the saved size/position, else show at the default size. */
    if (!RestoreWindowPlacement(g_main))
        ShowWindow(g_main, SW_SHOWNORMAL);
    UpdateWindow(g_main);

    /* Offer to recover text if the last session ended abnormally. */
    CheckRecovery();

    accel = LoadAcceleratorsA(g_inst, MAKEINTRESOURCEA(IDA_ACCEL));

    while (GetMessageA(&msg, NULL, 0, 0) > 0) {
        /* Let the modeless "Saving Audio" dialog handle its own keys (Tab to
         * Cancel, Esc/Enter) before the main window sees them. */
        if (g_progressDlg && IsDialogMessageA(g_progressDlg, &msg)) continue;
        if (accel && TranslateAcceleratorA(g_main, accel, &msg)) continue;
        if (IsDialogMessageA(g_main, &msg)) continue;
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }

    CoUninitialize();
    if (single) CloseHandle(single);
    return (int)msg.wParam;
}
