/* Generated by build.bat - edit the variables in build.bat, not here. */
#define SA_VER_MAJOR     2002
#define SA_VER_MINOR     1
#define SA_VER_PATCH     0
#define SA_VER_BUILD     0
#define SA_VERSION_STR   "2002.1.0.0"
#define SA_PRODUCT_NAME  "Speakalive"
#define SA_FILE_DESC     "Speakalive text-to-speech"
#define SA_COMPANY       "Seediffusion"
#define SA_COPYRIGHT     ""
#define SA_INTERNAL_NAME "cdfn.Speakalive"
#define SA_ORIG_FILENAME "Speakalive.exe"
#define SA_COMMENTS      "A revival of Speakonia."
